### ISSUE TITLE
FeatureRequest - customisable zoom range.

### ISSUE THREAD

**Issue by MattyBalaam** [ricardo-ch/react-easy-crop#10]
In my application I am working on the maximum zoom amount on an image so that it maps to 1pixel in source image at the maximum zoom.

I have noticed that if this value over 3 then I cannot use the scrollwheel to go beyond this point - although a range slider can break this maximum.

Ideally the component would use default props to set a minimum and maximum range and these could be overridden as required.

**Comment by MattyBalaam** [comment]
PR submitted: https://github.com/ricardo-ch/react-easy-crop/pull/11

**Comment by ValentinH** [comment]
Released with https://github.com/ricardo-ch/react-easy-crop/releases/tag/v1.3.0
