### ISSUE TITLE
Canvas size problem

### ISSUE THREAD

**Issue by redwallsolutions** [ricardo-ch/react-easy-crop#103]
## Are you reporting a bug?

Yes, but it's related to outputting cropped image.

[Sandbox Demo](https://codesandbox.io/s/react-easy-crop-demo-with-cropped-output-3khjf)

Steps to reproduce:

1. Just click to show result
2. Look at console

I think it's related to maximum canvas calculation. I noticed it occurs just after a `ctx.translate(safeArea / 2, safeArea / 2);`.

I've wondering if there's a another way to get the cropped image without doubling the canvas size. Because if we have current browser limitation about it, how can we enjoy this amazing package (btw, thank you, it's really nice) on current phone which take default pics with 6k~ width and height?

I'm attaching a print of real console error 
![Screenshot from 2020-03-02 11-56-29](https://user-images.githubusercontent.com/44881621/75688385-2c794080-5c7e-11ea-9d26-de5283992f84.png)
(once sandbox console doesn't describe the exception accurately)

**Comment by ValentinH** [comment]
I think this is the same issue as #98.
You need to resize the image before applying the transformations.

**Comment by redwallsolutions** [comment]
Once the application only use common rotation values (90º, 180º, 270º), I could workaround it by not doubling canvas size value limiting very large images. Apparently, images with naturalWidth or naturalHeight until 10k works fine. Thank you anyway.

**Comment by ValentinH** [comment]
Thanks for sharing the solution :)
