### ISSUE TITLE
Massive image size increase after cropping

### ISSUE THREAD

**Issue by sutefan1** [ricardo-ch/react-easy-crop#104]
Hey,

what's the reason for the massive increase in some pictures after cropping it? 

For example, one picture has ~2MB and after cropping it with its full size it has ~20MB. In our use case, we limit the size of uploaded pics on the client and server-side. This random behavior makes it had to check the size property as the user uploads a pic correctly but then gets an error that the image is too big.

Best,
sutefan

**Comment by ValentinH** [comment]
Hello,

Do you referrer to the crop code in the example sandbox? Also do you have an image example of the issue?

**Comment by sutefan1** [comment]
> Hello,
> 
> Do you refer to the crop code in the example sandbox? Also do you have an image example of the issue?

Hi @ValentinH,

I just figured out that if I change the `toBlob`-type at the end of the `getCroppedImg`-function of the sandbox example to `"image/png"` and try to crop a jpeg, then the picture's size goes up to over 20MB from 2MB original size. 

However, if I change it back to `"image/jpeg"` the size is slightly increased, like 2MB to 2,5MB.
