### ISSUE TITLE
How to raise the crop area on the photo above?

### ISSUE THREAD

**Issue by FillPower1** [ricardo-ch/react-easy-crop#112]
Hi! Me again)
Is there any way to raise the crop area higher?
Like on the picture, I did it through CSS, but it doesn’t work as it should.
Coordinates are not calculated correctly

![image](https://user-images.githubusercontent.com/46319022/78359245-572c2100-75bd-11ea-9d63-7af63860ade8.png)

**Comment by ValentinH** [comment]
Yes, you can simply set the initial `crop.y` value to something different than 0: https://codesandbox.io/s/react-easy-crop-demo-iw6hn

**Comment by FillPower1** [comment]
> Yes, you can simply set the initial `crop.y` value to something different than 0: https://codesandbox.io/s/react-easy-crop-demo-iw6hn

Hi!
I do as you said, but in my example it doesn't work
When loading an image, the image is shifted down, but the cropping zone remains in place in the middle
Upload a photo that is long in height and you will see
https://codesandbox.io/s/react-easy-crop-demo-5ru4b?file=/src/index.js
Please, help)

**Comment by ValentinH** [comment]
Yes, it's actually the case in my example. The original goal of this library is to have a fix crop area and the user moving the image under it. Thus, it cannot do what you want to achieve.

**Comment by ValentinH** [comment]
I'm closing this as everything has been said I think.
