### ISSUE TITLE
Could you please tell me which version is only react version instead of TS version?

### ISSUE THREAD

**Issue by elva329** [ricardo-ch/react-easy-crop#114]
Hi,

I found your repository which is awesome. Thank you sharing this component. 

However,  I only need the React version because currently I don't have any knowledge about TS yet,  could you please kindly tell which version or branch that contains only React with the feature "crop, zoom and rotate?

Thank you.

**Comment by ValentinH** [comment]
Hello,

First thing, this library is using Typescript starting from version 2 (see [the releases page](https://github.com/ricardo-ch/react-easy-crop/releases)).

However, the fact that we are now using Typescript to write this library should not matter for you. Indeed, the published npm package is fully in plain JavaScript. There is nothing to worry for you.
