### ISSUE TITLE
Editable shape of the crop

### ISSUE THREAD

**Issue by oyeanuj** [ricardo-ch/react-easy-crop#115]
Hi @ValentinH , thank you for creating this library!

I'm curious it is possible to let the user create the crop shape rather than giving a pre-determined width and height? So, a user could take an image and create a square crop or rectangular crop?

Apologies if I missed this option that already exists!

**Comment by ValentinH** [comment]
Hello,

The goal of this library is to provide a quick way of cropping an image with a predefined aspect/shape. The user cannot update the crop area size/aspect by dragging the edges.

I really recommend using https://github.com/DominicTobias/react-image-crop if you need a more classic cropping UI.

There is still the `cropSize` property that lets you change the dimension of the crop area at runtime. However, you need to build your own UI on top of it like with an input field or slider for the width and the height.

**Comment by di1606** [comment]
How to modify cropShape in rectangle without going through cropSize ? 

my question is due to the fact that every time I change the position of the image with props  `onCropComplete`, I have a error

**Comment by ValentinH** [comment]
You can use the `aspect` prop.

**Comment by kinucris** [comment]
> Hi @ValentinH , thank you for creating this library!
> 
> I'm curious it is possible to let the user create the crop shape rather than giving a pre-determined width and height? So, a user could take an image and create a square crop or rectangular crop?
> 
> Apologies if I missed this option that already exists!

Hello friends, I must admit that I came here to ask practically the same thing lol

I would like something similar to the _Polygonal Lasso Tool_ (existing in traditional image editing software such as **Photoshop**)

See example
![uapqNRW](https://user-images.githubusercontent.com/1749118/79997853-5ede3780-8490-11ea-8217-4b09f58d4e1a.gif)

**Comment by ValentinH** [comment]
Hi @kinucris , I'll be honest: I don't see at all how to achieve this kind of feature with the library. :)

**Comment by ValentinH** [comment]
Closing this as I think everything is answered.
