### ISSUE TITLE
Size adjustment while rotating ignores zoom

### ISSUE THREAD

**Issue by ValentinH** [ricardo-ch/react-easy-crop#116]
We have a feature that ensure that the crop area is always covering the image while rotating. However, we are not using the zoom parameter to compute it. This could be improved. See example:
![20200418_103931](https://user-images.githubusercontent.com/2678610/79632649-fa09a100-8160-11ea-8a17-765ab5994c77.gif)

**Comment by zlanich** [comment]
@ValentinH How would I accomplish this if I'm controlling zoom and rotation through Cropper props?

**Comment by ValentinH** [comment]
I'm not sure I understand the question. Indeed, controlling the zoom and rotation via props is the normal way of using this component. The demo in the screen recording above uses this pattern.

**Comment by zlanich** [comment]
@ValentinH  Yea, sorry, I probably wasn't clear, as I was mid-thought in figuring all this out. I interpreted 

> We have a feature that ensure that the crop area is always covering the image while rotating 

as the crop area will always be within the image itself, so you don't have void space outside the image. Correct me if I'm wrong. However, it doesn't appear to actually work that way--there is void space around the image when rotating. Is this already a known issued implied by you saying 

> This could be improved

?

Thanks!

**Comment by ValentinH** [comment]
Yes this is what I was implying, it was not really clear indeed :)

We cannot prevent the user from dragging the image to a point where some empty space is in the crop area. However, we could automatically adjust the zoom while rotating to avoid empty spaces. This is already done but the current zoom value is not used in the formula. This is what needs to be changed.

**Comment by zlanich** [comment]
Ok, that makes sense now. I'm currently trying to figure out how to work this into the Filepond uploader, but I'm not having success with the differing order of transforms, and this threw me off a just a bit more, haha.

If my math skills were stronger, I'd volunteer a PR.

**Comment by ValentinH** [comment]
Math skills is also an issue for me. I came up with most formulas in this project by first writing the unit tests for the results I was expected, then tweaked the formulas 😄 . For the rotation, it was nicely contributed by @MattyBalaam.

**Comment by MattyBalaam** [comment]
Don’t ask me how it works right now… there was a lot of trial and error involved :D

**Comment by zlanich** [comment]
@MattyBalaam I can imagine! Haha. If I get anywhere significant with it, I will look into a PR for documentation amendments. I will probably just use Doka for this particular client. Thanks!

**Comment by ValentinH** [comment]
I didn't know about Doka, nice stuff there :) I'm interested to know what features make you use it instead of this library?

**Comment by zlanich** [comment]
@ValentinH Mostly because it's a 5min drop-in for Filepond image uploader. I spent about 8hrs trying to get this lib working with that uploader, but the transforms are done in a different order, so after many stabs in the dark at linear algebra to apply the corrective math, I gave up lol.

**Comment by aguilera51284** [comment]
use this with filepond
```js
editor.onconfirm({
      data: {
        crop: {
          center: {
            x: (croppedArea.x + croppedArea.width / 2) / 100,
            y: (croppedArea.y + croppedArea.height / 2) / 100
          },
          flip: {
            horizontal: false,
            vertical: false,
          },
          zoom: zoom,
          rotation: 0,
          aspectRatio: (croppedAreaPixels.width / croppedAreaPixels.height),
        },
      },
    });
```

**Comment by ValentinH** [comment]
This was a bad idea after trying to implement it: in the original issue video, it would mean that zooming on a rotated image would do nothing until the container size is fit.

![Kapture 2020-08-16 at 18 07 18](https://user-images.githubusercontent.com/2678610/90338651-64393200-dfeb-11ea-80bb-a0dbdbdede37.gif)


I'm closing this.
