### ISSUE TITLE
Cannot zoom in if starting position of the slider is in the middle

### ISSUE THREAD

**Issue by TanKucukhas** [ricardo-ch/react-easy-crop#117]
##  BUG (Perhaps?)

I want my uploaded image to fit on the screen and the slider on the middle, if you slide left I want it to zoom out and zoom in when you slide right.

Te zoom out is perfectly fine it scales down to zero without any problem, but the zoom in only does a little bit which does not look enough.

I tried adding minZoom={0} maxZoom={100} and initial value of {50}, but that does not seem to work. Looks like original size is fixed to always 0.5 so you are forced to do between 0 to 1 if you want to scale up and down.

Ideally, I would like to control the range so that I can zoom in more. Am I missing some steps to accomplish this?

Here is the sandbox:
- https://codesandbox.io/s/gracious-curran-1j98h?file=/src/index.js

**Comment by TanKucukhas** [comment]
when my slider is set to minZoom: 0 MaxZoom: 10 and zoom set to 5, I expect the starting position of the image to be originalsize, instead it shows up zoomed in.

https://codesandbox.io/s/gracious-curran-1j98h?file=/src/index.js

**Comment by ValentinH** [comment]
The `zoom` property is directly applied to the `transform: scale(zoom);` css rule.

Thus, the "no zoom" value is 1. 0 will just show nothing, etc...

I've checked your demo and the zoom value is correctly applied to the image.

**Comment by TanKucukhas** [comment]
Thanks for the quick reply @ValentinH. I have not realized it was directly using scale(zoom).  In that case, `1` is always to the original size.  

Is there a way to fit the image to the crop-size initially?

**Comment by ValentinH** [comment]
Do you have a particular reason to use the `cropSize` instead of the `aspect`? Indeed, `aspect` will automatically adjust the image while cropSize is for more manual usage.

**Comment by TanKucukhas** [comment]
I need the output image to be square regardless of the aspect ratio of what is uploaded, that is my only restriction. Essentially I want people to upload their logos and zoom in zoom and crop.

**Comment by ValentinH** [comment]
Ok then you can set the aspect to 1 🙂

**Comment by TanKucukhas** [comment]
When I set the aspect to 1, the image still does not fit the box.

https://codesandbox.io/s/romantic-rosalind-w31cg?file=/src/index.js

**Comment by ValentinH** [comment]
If you set `restrictPosition` to `true`, `zoom` to 1 and `aspect` to 1, the crop area will match the height of the image.

**Comment by TanKucukhas** [comment]
Sorry, still does not seem to be doing it;
https://codesandbox.io/s/romantic-rosalind-w31cg?file=/src/index.js

**Comment by ValentinH** [comment]
On load, the library will always match the smallest side of the image with the crop area. The goal is to never have an 'empty space' within the crop area. Thus if you have a square crop area and a rectangle image, it will always be fit vertically.

**Comment by TanKucukhas** [comment]
Thanks @ValentinH, understood I think it makes sense for the most images. But when it comes to logos you would always want it to fit on both sides. Not sure if my case is rare but I think It would be nice to have to option to fit from both sides.

**Comment by ValentinH** [comment]
Fitting on both sides would mean that we end up having some empty space in the image (resulting in white/black in the output), right?

**Comment by TanKucukhas** [comment]
Logos usually have transparent backgrounds or plain white. In both cases, it works fine. You can draw any color on the background if the background is transparent.

**Comment by ValentinH** [comment]
I see. Anyway, this is something that is not supporting by this library right now. You could suggest a new option and try to work on a PR, but I'd like to avoid adding another option just for one specific use case.

**Comment by TanKucukhas** [comment]
Sounds good thanks a lot for your help.

**Comment by ValentinH** [comment]
Can I close this issue?

**Comment by naveensomanna** [comment]
logos with no background color after cropping setting black background anyone facing the same issue?

**Comment by TanKucukhas** [comment]
Yes we can
