### ISSUE TITLE
Setting cropSize prop makes component crash / infinite loop

### ISSUE THREAD

**Issue by desduvauchelle** [ricardo-ch/react-easy-crop#118]
## Bug

Setting the `cropSize` prop on the component creates an infinite loop on local and a crash in sandbox.

Sandbox: [https://codesandbox.io/s/react-easy-crop-custom-image-demo-xwv8k?file=/src/index.js](https://codesandbox.io/s/react-easy-crop-custom-image-demo-xwv8k?file=/src/index.js) 
_I simply added `cropSize={{ width: 200, height: 200 }}` as a prop into one of your demos_

### Steps

1) Load [sandbox]( https://codesandbox.io/s/react-easy-crop-custom-image-demo-xwv8k?file=/src/index.js ) 
2) Select an image
3) View console for crash info

**Observed behaviour:** crash / Infinite loop
```
Invariant Violation
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```
**Expected behaviour:** Output image size to specified crop size.

**Comment by ValentinH** [comment]
Hello,

Please consider the warning in the documentation
> This property is rerendering the component when changed so you need to ensure that you are not providing a new object instance at each render. 

You can simply fix it by storing your cropSize in the state of in a variable outside the component.

**Comment by desduvauchelle** [comment]
Hi Valentin, 

Thanks for reaching back. 
I had seen that but since it wasn't a variable, I was just declaring it, I thought it didn't apply. 

Sorry and thanks for this great library!

**Comment by desduvauchelle** [comment]
If anyone else is confused by this, I did this:
```js
const cropSize = { width: 200, height: 200 }

const MyComponent = () =>{
   // ......
   return <Cropper // ...other attributes
                cropSize={cropSize} />
}
```
