### ISSUE TITLE
Can the cropped image blob url be converted to an image file ?

### ISSUE THREAD

**Issue by elva329** [ricardo-ch/react-easy-crop#119]
Hi,

I have a question, can the cropped image url (blob:http://localhost:3000/3c6b55b6-f8b9-4ce0-a91b-ad2d77cb5cf7) be converted to an image format file(.jpg)  ?

Thank you.

**Comment by ValentinH** [comment]
Hello,

There is nothing specific to this library, what you are looking for can be found on StackOverflow: https://stackoverflow.com/questions/27159179/how-to-convert-blob-to-file-in-javascript/29390393

I'm closing this issue as it is more of a support request.
