### ISSUE TITLE
Feature Request: Scrollwheel zoom into point

### ISSUE THREAD

**Issue by MattyBalaam** [ricardo-ch/react-easy-crop#12]
As a user when I have my mouse cursor over a point on an image I would expect it to zoom into that point as the origin.

**Comment by ValentinH** [comment]
You are right, this would be nice. In the same idea, when zooming on mobile with 2 fingers, we should also use the center of the 2 points  as the zoom origin.

This is more complex to compute but it's still doable. Would you like to implement this?

**Comment by MattyBalaam** [comment]
I started to take a crack earlier, but it may take a while for me to find the time to implement it well.

**Comment by ValentinH** [comment]
I'll try to look into this when I have a bit of time 🙂

**Comment by ValentinH** [comment]
@MattyBalaam Here's a first try, could you tell me if it matches what you meant? (only wheel is handled in this demo):
https://codesandbox.io/s/mj61vp82xp

**Comment by ValentinH** [comment]
Nevermind, this is already better but not exactly what you requested. I need more work I think.

What you meant is probably something like this: http://phrogz.net/tmp/canvas_zoom_to_cursor.html

**Comment by MattyBalaam** [comment]
I gave the PR a try and it works great on my mousewheel.

**Comment by ValentinH** [comment]
OK, I'll need to clean the code a bit and at least ensure that the zoom with pinch is still working. I could add the same feature for pinch later. 🙂

**Comment by MattyBalaam** [comment]
Ah, yes. you shouldn’t rely on me as a tester that’s for sure.

**Comment by ValentinH** [comment]
No I think it's ready: https://codesandbox.io/s/mj61vp82xp.

It also handles mobile zoom too. :)

**Comment by MattyBalaam** [comment]
Just tried it on desktop and on my Android phone and it works brilliantly. Brilliant job.

**Comment by ValentinH** [comment]
Ok I'll release this later today once I'm on the computer :)

**Comment by ValentinH** [comment]
Released as v1.4.0: https://github.com/ricardo-ch/react-easy-crop/releases/tag/v1.4.0
