### ISSUE TITLE
Can we get the cropped image without using the putImageData method ?

### ISSUE THREAD

**Issue by elva329** [ricardo-ch/react-easy-crop#120]
Instead of using putImageData method, can we get the cropped image ?

**Comment by ValentinH** [comment]
Where do you see `putImageData`?

**Comment by elva329** [comment]
I saw the putImageData function in the ImageCrop.js, which is used to generate the cropped image I think. However using this function, the image on the Android photo will get a little darker than the original one after crop. I searched online, it is said it is chrome issue. So I am trying to ask you if there’s other ways to generate the cropped image?

Thank you.

Regards,
Jia

**Comment by elva329** [comment]
One notice, when I used your component to generate cropped image on IOS phone, the image became total black (occurs for photo taken only) I checked the recommended solution on your issue list,  I reduced the safeArea and the black issue was resolved on iOS. However after this change, the image on Android phone will become a little darker after crop which related to my previous comments. So I am wondering if there are other ways to generate the cropped the image in other ways or any tricks to set the safeArea to a proper value so that the cropped image can be displayed correctly both on Android and iOS?

Thank you.

Regards,
Jia

**Comment by ValentinH** [comment]
I don't know anything else than this method. Actually, this file is not part of the library and is just an example to give a hint about how to crop the image client-side. This is not part of the library itself.

You can also check this other approach: https://github.com/DominicTobias/react-image-crop#what-about-showing-the-crop-on-the-client
I used to use this technique but it didn't support rotation so this is why we changed.
