### ISSUE TITLE
How to zoom with a fixed button

### ISSUE THREAD

**Issue by FillPower1** [ricardo-ch/react-easy-crop#121]
Hi! Please tell me is it possible to do as in this video.
https://drive.google.com/open?id=1sZkRGnV7h4vu30Db0r81PeddPW8ioq_A

I tried, but it didn't work out right. Is there a better way?

**Comment by ValentinH** [comment]
Nope there is no built-in feature for it .

**Comment by FillPower1** [comment]
Do you have any ideas how to implement this? To link to the library

**Comment by ValentinH** [comment]
I don't see a way to achieve this without forking the library.

**Comment by FillPower1** [comment]
Ok, can you tell me how not to block the scroll window from the container so that the page scrolls
I changed the movement of the image inside the cropping zone

**Comment by ValentinH** [comment]
You would need to remove the lines where we prevent the default behavior, like https://github.com/ricardo-ch/react-easy-crop/blob/master/src/index.tsx#L231

**Comment by FillPower1** [comment]
It doesn't work(
I need the document scroll to work in the mobile version
I deleted lines 231 and 243
https://github.com/ricardo-ch/react-easy-crop/blob/master/src/index.tsx#L231
https://github.com/ricardo-ch/react-easy-crop/blob/master/src/index.tsx#L243

**Comment by FillPower1** [comment]
I checked, for some reason it works on iPhones, but not on Android. When I move my finger over the image(not the cropping area), the page doesn't scroll

**Comment by FillPower1** [comment]
Close. Solved the problem by using pointer-events. Thanks!
