### ISSUE TITLE
Filetypes and maximum file size specs

### ISSUE THREAD

**Issue by TanKucukhas** [ricardo-ch/react-easy-crop#122]
I could not find it in the docs. Is there any documentation for what is accepted file types and what is maximum/minimum file size the crop library can handle?

Also, I have not seen any error handling so I assume we need to handle that right after file change event.

Thanks.

**Comment by ValentinH** [comment]
Hello,

Regarding file type, you can pass any format handled by the `img` or `video` tag. I don't know any restrictions about size.

For error handling, you can pass the onError callback by using the `mediaProps` property.

**Comment by TanKucukhas** [comment]
Thanks, this was helpful.
