### ISSUE TITLE
Invariant violation: Maximum update depth exceeded when using crop size

### ISSUE THREAD

**Issue by jmorey28** [ricardo-ch/react-easy-crop#123]
## Are you reporting a bug?
yes

- Please create a CodeSandbox that demonstrates your issue. 
https://codesandbox.io/s/zen-chaplygin-t2jbk

- Provide the steps to reproduce the issue, e.g.:

1. using version 2.1.1 add cropSize prop to component, with 200 for width and height (seems to be with any values)

  **Observed behaviour:** Maximum update depth exceeded error
  **Expected behaviour:** Should allow cropSize without error

**Comment by ValentinH** [comment]
Please see #118

**Comment by jmorey28** [comment]
great thanks!
