### ISSUE TITLE
Ability to pass desired output size or dimensions.

### ISSUE THREAD

**Issue by TanKucukhas** [ricardo-ch/react-easy-crop#124]
I think this is a fair use case. Say I set my crop area to 100px 100px and I want my output to be 200px 200px so that it is 2X the resolution. If the user uploads a huge image and crops the image based on my crop area even though the area is 100px 100px the final output can be way large like 2400px 24000px due to uploaded image resolution.

This issue is more apparent if you zoom out from your original size, the uploaded image size gets bigger. so theoretically you can upload a 2mb image and have a 10mb output image for a 100px 100px crop area.

I try to modify the output here but for some reason, it is blank when I change it to fixed values

` 
// set canvas width to final desired crop size - this will clear existing context
 canvas.width = 400
 canvas.height = 400
`

It would be very useful if I could control the desired output height or a max image size so that the file does not get bloated.

Perhaps something like this along with the croparea

`
<ReactEasyCrop
      cropSize={{height: 200, width: 200}}
      outputCropSize={{height: 400, width: 400}}
  />
`

**Comment by ValentinH** [comment]
If I understand correctly what you want, it should already be possible today. Indeed, the crop output only tells you what part of the image was selected by the user. You are then free to resize this piece of image to whatever size you want.
For example, on Ricardo.ch, we limit the output dimension to 1800px before uploading the image to our servers.
You can adapt the crop output example code to resize the image when doing the canvas editing.

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉

**Comment by carloslibardo** [comment]
@ValentinH can u help me?

In my case i have a crop size of width = 444 and height = 250.

My input image has width = 450 and height = 50.

To calculate correct scaled zoom i do that:

```
const zoomX = 444/width;
const zoomY = 250/height;
const scaledZoom = Math.max(zoomX, zoomY);
```

Then my scaledZoom is 3.8461538461538463.
And this is my crop area:
![image](https://user-images.githubusercontent.com/11881938/95497576-ea814d00-0978-11eb-9080-a7ef771f2bde.png)

This is my output image:
![image](https://user-images.githubusercontent.com/11881938/95497671-1997be80-0979-11eb-998f-1f8550a4e4f1.png)

I want to save image with the same crop size, but i don't know how, any inputs?
