### ISSUE TITLE
Browser hangs till cropping

### ISSUE THREAD

**Issue by Abilashinamdar** [ricardo-ch/react-easy-crop#128]
It seems like when I try to crop large size images the whole browser hangs till it crops. This happens if I try to crop more than 1MB file.

**Comment by ValentinH** [comment]
How are you croping the image?

**Comment by Abilashinamdar** [comment]
Below link is the sandbox link which is mentioned in the [demo](https://ricardo-ch.github.io/react-easy-crop/). Try to choose an image which is more than 1MB and it hangs for sometime till it croops.


[https://codesandbox.io/s/react-easy-crop-custom-image-demo-y09komm059?from-embed](url)

**Comment by ValentinH** [comment]
Cropping the image is CPU intensive. You can display a loader while the image is being cropped, but the loader might be laggy as well (depends if the animation runs on the GPU).

You can also try using https://github.com/nodeca/pica to actually crop the image. 

If you don't need to support the rotation, you can probably make the demo function a bit faster.

Anyway, the cropping code is not part of this library so I'm going to close this issue.
