### ISSUE TITLE
Logarithmic Zoom Delta on Mouse wheel

### ISSUE THREAD

**Issue by jamespedid** [ricardo-ch/react-easy-crop#132]
## Are you making a feature request?
- Please describe your use case from user journey point of view, e.g.:
The scrolling of the zoom parameter is not linear due to the nature of zooming math. Exponentials and logarithms should be used for proper effect.

When setting a min zoom of 1/10 and a max zoom of 10, the mouse wheel of the zoom is 
 unbalanced in terms of the amount of zoom that you get per 'delta y'; when the zoom is around 1, the zoom changes much faster than when around the maximum and minimum values.

- If you have ideas how to implement your new feature, please share!

The reason for this is due to the calculation of new zoom. Instead, if you use proper base ten logarithm in the coordinates, then the zoom would be linear.

`newZoom = zoom - deltaY * zoomSpeed / 200`

 should instead become

```
zoomTValue = Math.log10(zoom);
minZoomTValue = Math.log10(minZoom);
maxZoomTValue = Math.log10(maxZoom);
newZoomTValue = zoomTValue - deltaY * zoomSpeed * (maxZoomTValue - minZoomTValue) // maybe scale it by the 200 here
newZoom = Math.pow(10, newZoomTValue);
```

**Comment by ValentinH** [comment]
Thanks for the feature request. I think it makes sense. Would you like to submit a PR for this?

**Comment by jamespedid** [comment]
I'll give it a crack a little later tonight.

**Comment by jamespedid** [comment]
Ended up doing it now while I had a bit of free time waiting for a meeting. Take a look. I'd personally recommend making it the default behavior because I think it gives a more natural scrolling effect.

**Comment by ValentinH** [comment]
Closing this now as no one else requested this feature. We are not going to implement this.
