### ISSUE TITLE
Bad cropper size on portrait image with rotation

### ISSUE THREAD

**Issue by TiTnOuK** [ricardo-ch/react-easy-crop#141]
- CodeSandbox

  1. Portrait image => https://codesandbox.io/s/xenodochial-smoke-45re7
  2. Landscape image =>  https://codesandbox.io/s/old-cookies-f68z7

---

- Steps to reproduce the issue :

  1.  Rotate the image 90 degrees

---

  **Observed behaviour:** 
Portrait image => The size of the cropper not adapt to the image
Landscape image => The size of the cropper adapt to the image

  **Expected behaviour:** 
In case with portrait image, the size of the cropper should adapt to the image

**Comment by ValentinH** [comment]
Do you mean that it should zoom the image automatically to this point?
![image](https://user-images.githubusercontent.com/2678610/82895162-0ea53a00-9f54-11ea-9a8d-6f624a6550f8.png)

**Comment by TiTnOuK** [comment]
Yes exactly.
I have the impression that this is what is done for images in landscape

**Comment by ValentinH** [comment]
Yes probably. Would you like to work on a pull request? I think the magic should be done here: https://github.com/ricardo-ch/react-easy-crop/blob/master/src/index.tsx#L216

**Comment by pranavmehta** [comment]
This should probably be controlled via an optional setting and not the default behaviour. In my case, I always want the user to crop in portrait mode regardless of the rotation of the image - useful when a portrait is desired but the phone's camera has messed up the orientation or when a portrait crop is needed from a landscape image.

**Comment by ValentinH** [comment]
@TiTnOuK I actually noticed that this was fixed in the last version while writing on other issues with portrait 🥳 could you please confirm?

@pranavmehta I'm not sure to understand what you mean, does the behavior in the demos above match what you want?

**Comment by TiTnOuK** [comment]
@ValentinH I confirm, it's works perfectly now. Good Job 👍
