### ISSUE TITLE
Canvas Area size limit issue on all devices

### ISSUE THREAD

**Issue by Xx-AmrHossam-xX** [ricardo-ch/react-easy-crop#142]
Summary:
##When i try to upload an image which has a relevant high width or height or both , the image goes through the code of the cropper and while the image is being drawn into a canvas that high width/height/both is inturn transferred to the canvas which produces the error in my project "warning canvas area size limit exceeded".The canvas area size limit varies from one device to another so the image that would fail for example on an iphone device would work fine on a laptop however if you upload the attached images, they would produce the same error on a laptop because they do exceed the max canvas area size limit for laptops.Spoiler : I tried the crop size parameter and it did not work.

-This is the example which i based my code on :
 https://codesandbox.io/s/y09komm059
-To be able to see the my issue on laptop devices , you can try to upload the images i attached
![sergio-rodriguez-gu48Rd26TtM-unsplash](https://user-images.githubusercontent.com/40577354/83770341-3ea1bb00-a681-11ea-953f-304e23b4758b.jpg)

![ales-krivec-wC69cxOE7Us-unsplash](https://user-images.githubusercontent.com/40577354/83770541-79a3ee80-a681-11ea-960c-f7f15c6d61b8.jpg)

![5Mb](https://user-images.githubusercontent.com/40577354/83770668-9f30f800-a681-11ea-9fb4-432b99471f12.jpg)

- Steps to reproduce the issue:

1-Upload an image which exceeds the canvas area size limit of a certain device 
2-Submit 

NOTE:

#Adding this as a parameter  on the cropper component neither solves the problem on the sandbox example or in my project :  

"  cropSize={{width:100,height:100}}   "

  **Observed behaviour:** No result appears in the sandbox example on codesandbox
and in my project after i convert the result into an image file then send it to another api to save it then i get the result , the result is just a black image .The result is a corrupted image.

  **Expected behaviour:** The cropper should either stop the canvas width and height from reaching the canvas area limit for any device OR the library should give the option to the developer to choose a certain canvas width and height to input to the library as a parameter.

What is my modification to the file i downloaded from the example ?
1-I pass an additional argument "SizeIndicator"  if true the quality of the image in the canvas.toBlob function is 0.1 , else it is defaulted to 100.
2-At the end i convert the result into an image file 
This is the code in the js file where the actual cropping happens :
"const createImage = (url) =>
  new Promise((resolve, reject) => {
    const image = new Image();
    image.addEventListener("load", () => resolve(image));
    image.addEventListener("error", (error) => reject(error));
    image.setAttribute("crossOrigin", "anonymous"); // needed to avoid cross-origin issues on CodeSandbox
    image.src = url;
  });

function getRadianAngle(degreeValue) {
  return (degreeValue * Math.PI) / 180;
}

/**
 * This function was adapted from the one in the ReadMe of https://github.com/DominicTobias/react-image-crop
 * @param {File} image - Image File url
 * @param {Object} pixelCrop - pixelCrop Object provided by react-easy-crop
 * @param {number} rotation - optional rotation parameter
 */
export default async function getCroppedImg(
  imageSrc,
  pixelCrop,
  rotation = 0,
  SizeIndicator
) {
  const image = await createImage(imageSrc);
  const canvas = document.createElement("canvas");
  const ctx = canvas.getContext("2d");

  const safeArea = Math.max(image.width, image.height) * 2;
  // console.log(safeArea, "safeArea");
  // set each dimensions to double largest dimension to allow for a safe area for the
  // image to rotate in without being clipped by canvas context
  canvas.width = safeArea;
  canvas.height = safeArea;
  // console.log(canvas.width, "width", canvas.height, "canvas.height");
  // translate canvas context to a central location on image to allow rotating around the center.
  ctx.translate(safeArea / 2, safeArea / 2);
  // console.log(ctx, "CTX");
  ctx.rotate(getRadianAngle(rotation));
  ctx.translate(-safeArea / 2, -safeArea / 2);

  // draw rotated image and store data.
  ctx.drawImage(
    image,
    safeArea / 2 - image.width * 0.5,
    safeArea / 2 - image.height * 0.5
  );
  const data = ctx.getImageData(0, 0, safeArea, safeArea);

  // set canvas width to final desired crop size - this will clear existing context
  canvas.width = pixelCrop.width;
  canvas.height = pixelCrop.height;

  // alert(
  //   "1st " +
  //     canvas.width +
  //     " width " +
  //     canvas.height +
  //     " height " +
  //     canvas.width * canvas.height +
  //     " area "
  // );

  // paste generated rotate image with correct offsets for x,y crop values.
  ctx.putImageData(
    data,
    0 - safeArea / 2 + image.width * 0.5 - pixelCrop.x,
    0 - safeArea / 2 + image.height * 0.5 - pixelCrop.y
  );

  // As Base64 string
  // return canvas.toDataURL('image/jpeg');
  // As a blob
  return new Promise((resolve) => {
    if (SizeIndicator) {
      canvas.toBlob(
        (file) => {
          // alert(
          //   file.size / 1000000 +
          //     " file.size " +
          //     SizeIndicator +
          //     " SizeIndicator "
          // );
          resolve(
            new File(
              [file],
              "image" + Math.floor(Math.random() * (100 - 1)) + 1 + ".jpeg",
              {
                type: "image/jpeg",
              }
            )
          );
        },
        "image/jpeg",
        0.1
      );
    } else {
      canvas.toBlob(
        (file) => {
          // alert(
          //   file.size / 1000000 +
          //     " file.size " +
          //     SizeIndicator +
          //     " SizeIndicator "
          // );
          resolve(
            new File(
              [file],
              "image" + Math.floor(Math.random() * (100 - 1)) + 1 + ".jpeg",
              {
                type: "image/jpeg",
              }
            )
          );
        }
        // ,
        // "image/jpeg",
        // 0.1
      );
    }
  });
}
"

**Comment by ValentinH** [comment]
This is exactly why the actual cropping of the image is not done by the library: there are a lot of edge cases. I only provide an example on Codesandbox to show how it can be done, however, issues coming from this logic is not part of this library.

One approach you could do here is restrict the size before doing the canvas operations in the client.

**Comment by ValentinH** [comment]
I'm sorry, I have limited bandwidth at the moment and no time to help for something that I don't support.

**Comment by Xx-AmrHossam-xX** [comment]
The main reason why anyone would use this library is because he needs to crop an image in react.I'm not convinced that the action of cropping the image is considered by you as a low priority !

**Comment by ValentinH** [comment]
It's not low priority and this is why I wrote several examples. However, I'm not going to provide extensive support for this.

Please remember that you are able to use the library for free. Feel free to submit a PR with better guidelines or examples.
