### ISSUE TITLE
Instagram-like cropper

### ISSUE THREAD

**Issue by wendydv1989** [ricardo-ch/react-easy-crop#145]
Hello, 

thank you so much for this great lib. I'm tying to use this lib to build an Instagram clone front-end. So I was wondering how to config or fork the lib to do following things:
- When uploading an image, zoom to width of the uploaded image
- When uploading image that's too small for width of Cropper, give error.

I really like this lib, keep up the great work team! <3

**Comment by ValentinH** [comment]
Hi, thanks for the kind words!

I'm sorry but I'm not sure to understand what you want with your first point. Could you please explain a bit more or share some drawings/images showing what you want to achieve?

For the error part, you can implement it outside this library, before passing the image to the Cropper.

**Comment by wendydv1989** [comment]
Thanks for replying. 
When uploading a picture, the width of the picture should be equal to the width of the cropper. Even if the image is smaller or bigger than the cropper. 
When double tapping the picture, the height of the picture is used for the scaling.

**Comment by ValentinH** [comment]
The link leads to a 404.

With the default setting off the Cropper (using the aspect prop and not the cropSize), it automatically adjusts to the width (or the height depending on the ratio).

**Comment by wendydv1989** [comment]
I'll give it another shot. If not ill send u a link to my build to get a better view on what I' trying to do. Thanks for your support!

**Comment by ValentinH** [comment]
Hi, any update on this?
