### ISSUE TITLE
Image Black on iPhone XS

### ISSUE THREAD

**Issue by cravend** [ricardo-ch/react-easy-crop#147]
## Are you reporting a bug?

- The [Custom Image](https://codesandbox.io/s/y09komm059) example is what I'm using.

### Steps to Reproduce

1. Upload an image on an iPhone
2. Click show result

  **Observed behaviour:** The displayed output is a black image

  **Expected behaviour:** The cropped image is displayed

**Comment by ValentinH** [comment]
This is similar to #91 and #98.

I'm closing this as this is not an issue with the library itself and solutions has been shared on these issues?
