### ISSUE TITLE
Ability to change/match the blackspace background color of a cropped image

### ISSUE THREAD

**Issue by trinityEon** [ricardo-ch/react-easy-crop#148]
When you rotate an image to 45 degrees that has a predominantly white background, The empty space is currently filled in black. as per the cropped image in the example below

Is it possible to change the color of the filled in black, either automatically where it would select the predominant pixel color, or the user could select a background fill color from a color picker

<img width="677" alt="Screenshot 2020-06-22 at 10 33 35" src="https://user-images.githubusercontent.com/1106670/85266232-dcfc9180-b473-11ea-9202-fc562a323827.png">

**Comment by ValentinH** [comment]
Yes, this can ba done in user land, see this demo: https://codesandbox.io/s/react-easy-crop-demo-with-cropped-output-m0spo?file=/src/styles.js

The component doesn't have a background itself, the background in the demo is set in the parent container. Then, when doing cropping operation in client-side, you can simply set the initial background of the canvas with:

```js
ctx.fillStyle = 'white'
ctx.fillRect(0, 0, canvas.width, canvas.height)
```

**Comment by trinityEon** [comment]
Wow, Thank you for such a speedy response. This was either not documented or I missed reading about it. Hopefully it helps someone else too.

**Comment by ValentinH** [comment]
Actually, this is not really part of the library itself. The actual cropping logic is just provided as an example.

**Comment by skyylabz** [comment]
hey so this worked for me until i tried to fix the mobile issue by making the sfe are smaller this is what is did to fix that..

`const safeArea = Math.max(image.width, image.height) * 1`

but then now even with 

`ctx.fillStyle = 'white'
  ctx.fillRect(0, 0, canvas.width, canvas.height)`
 
the black background shows up again.. any ideas??
