### ISSUE TITLE
Add custom styling

### ISSUE THREAD

**Issue by tafelito** [ricardo-ch/react-easy-crop#15]
I'd like to add some custom stying to the cropper container, like changing the background colo. Is it possible to add some styling as a prop for the container? 

Thanks

**Comment by ValentinH** [comment]
Indeed, we could add some props to pass a class to be applied on the container and the cropper. 👍 

Would you like to submit a PR for this?

**Comment by bexoss** [comment]
@ValentinH I saw PR from him, could you commit? I need that features also ^-^

**Comment by tafelito** [comment]
@ValentinH, when do you think you'll publish a new version?
