### ISSUE TITLE
for a portrait image on rotation moves crop Rect outside image

### ISSUE THREAD

**Issue by SamirNvi** [ricardo-ch/react-easy-crop#152]
Hi Valentin/ support ,

Thanks for this wonderful free library. It works nice for me.
I am facing a issue for portrait images. I Have portrait images with aspect ratio set to say 0.66. when i rotate the image to 90 degree my crop rect doesnt change and it stays outside image . i am setting the initial crop area as center cropped area of image.

pls help me to resolve this issue.

![image](https://user-images.githubusercontent.com/25320256/87024179-66db8700-c1f6-11ea-9f73-9277118578ea.png)

after rotate
![image](https://user-images.githubusercontent.com/25320256/87024409-b457f400-c1f6-11ea-9f6f-534921195aa3.png)

**Comment by ValentinH** [comment]
Thanks for the kind words.

It looks like a bug indeed, could you please create a code sandbox showing the issue?

**Comment by ValentinH** [comment]
After checking this bug, it's related to #151. Basically, vertical aspects/images are not properly handled and the internal `getCropSize()` needs to be improved.

**Comment by ValentinH** [comment]
This should be fixed by #157, could you please test it (using the sandbox linked in the PR) and confirm?

**Comment by ValentinH** [comment]
Fix release with v3.1.1
