### ISSUE TITLE
On load, if image is a larger dimension than reactEasyCrop_Container don't resize reactEasyCrop_Image to fit.

### ISSUE THREAD

**Issue by Thiedent** [ricardo-ch/react-easy-crop#153]
As the title says, i am using a fixed zoom level of 1, and the container that contains <Cropper/> is a fixed size, say 400x350px, unfortunately when an image is uploaded that is a greater size this, the image resizes to fit the container rather than staying its original size.
 
I would be very appreciative if there is a solution to this or you could add it as a feature, as i can't use it how i need to otherwise.

Besides that it is a great package, thanks!

**Comment by ValentinH** [comment]
I think there is a misunderstanding of how the zoom value works. 1 means the image isn't zoomed so this is why it needs to be adjusted to match its parent container.

You could achieve what you want by pre-computing the zoom value: if your container is 400px wide and your image is 800px wide, set the zoom value to 2.

**Comment by Thiedent** [comment]
Sorry i don't think i understand, when you say,  "1 means the image isn't zoomed", this doesn't appear to be the case.

Leaving the zoom at 1 and loading an image causes the image to resize to the parent container if the images dimensions exceed the parent containers, which is not what i want, i want there to be no changes to the images size upon load. 

Apologies if I've misunderstood, if i have, i would prefer to not have to compute the zoom level based on the images dimensions.

**Comment by ValentinH** [comment]
The goal of this library is to be responsive and works on any screen size/aspect. When I say that the image is not zoomed, I mean that the result of the crop (not what you see in the component, which is just a preview) will not be zoomed.

You can play with this example which provide a crop output to better understand: https://codesandbox.io/s/q8q1mnr01w

**Comment by ValentinH** [comment]
Any thing new here? Can I close this issue?
