### ISSUE TITLE
Not able to crop image with barcode

### ISSUE THREAD

**Issue by codei20** [ricardo-ch/react-easy-crop#158]
## Are you reporting a bug?

I get a black image when I try to crop an image with barcode.

Test image:
![barcode](https://user-images.githubusercontent.com/68557987/87964469-eaf7ff00-ca7f-11ea-8d9c-bc95e3cd14ff.png)

- Provide the steps to reproduce the issue, e.g.:

 1. Crop image with barcode (see test image)

  **Observed behaviour:** I get a black image 
  **Expected behaviour:** cropped  barcode image

Please save the test image and try using the below example:
https://codesandbox.io/s/y09komm059

**Comment by ValentinH** [comment]
I guess this is because this is a PNG without a background. You can force the canvas to have a white background in the `cropImage` file logic.

**Comment by codei20** [comment]
Thanks for the quick response. Below changes to cropImage file worked.

 // translate canvas context to a central location on image to allow rotating around the center.
  ctx.translate(safeArea / 2, safeArea / 2)
  ctx.rotate(getRadianAngle(rotation))
  ctx.translate(-safeArea / 2, -safeArea / 2)
// force background to white. 
  ctx.fillStyle = "#FFF";
  ctx.fillRect(0, 0, canvas.width, canvas.height);
