### ISSUE TITLE
Image position changes after rotation on re-render

### ISSUE THREAD

**Issue by mforman1** [ricardo-ch/react-easy-crop#159]
## Summary
After rotation the image position changes on re-render.

## Observed behavior:
 The image position (i.e. `crop.x`) changes
  
## Expected behavior:
The image should stay on the same position after re-render

## Steps to reproduce:
  1.  Rotate the image
  2.  Re-render the page by clicking on the `Counter` button
  3.  Observe the console- the `x` changes on each page render.

## Code Sandbox:
https://codesandbox.io/s/fervent-haze-0n7fr?file=/src/index.js:876-974

**Comment by ValentinH** [comment]
I'm not sure to understand what you are trying to do. You seem to be mixing the `crop` data and the `initialCroppedAreaPixels` data which do not contain the same kind of data.

Could you please describe what feature you are implementing?

**Comment by mforman1** [comment]
What I'm trying to do is to keep the image state on the parent component in order to keep the changes made to the image after re-render.
On my project I implement `react-easy-crop`, after closing the preview-mode the image goes back to the default state, that's the reason I added: 
```
  const x = imageData.crop ? imageData.crop.x : 0
  const y = imageData.crop ? imageData.crop.y : 0
  const [crop, setCrop] = useState({ x, y })
  const [zoom, setZoom] = useState(imageData.zoom)
  const [rotation, setRotation] = useState(imageData.rotation)
```

**Comment by ValentinH** [comment]
In order to keep the state in the parent, you should actually store it there and only there. It's always a pain to keep two state in sync.

Thus, keep crop, rotation and zoom in the parent and update them via callbacks.

**Comment by mforman1** [comment]
Thank you, will try that, 
the "natural" state for this props (`crop`, `rotation` and `zoom` ) is on the editor component and not on the parent so I tried to avoid that.
There is no need for the `onCropComplete` prop?

**Comment by ValentinH** [comment]
The `onCompleteCrop` is a callback that is used at the end of an interaction. It should be used if you want to get the actual selected rectangle in pixels (or percent) on the image. This can be used to actually crop the image and display the preview.

**Comment by mforman1** [comment]
> In order to keep the state in the parent, you should actually store it there and only there. It's always a pain to keep two state in sync.
> 
> Thus, keep crop, rotation and zoom in the parent and update them via callbacks.

That actually what was causing the issue, I moved the cropper state to the parent and now it works as expected.
Thank you for the example you added, was very helpful,
Much appreciated!
