### ISSUE TITLE
Way to prevent canvas resize on rotation

### ISSUE THREAD

**Issue by gracelauren** [ricardo-ch/react-easy-crop#163]
## Are you reporting a bug?

- https://codesandbox.io/s/q8q1mnr01w

- Provide the steps to reproduce the issue, e.g.:

  1.  Rotate the image

  **Observed behaviour:**The cropper canvas stays the same size

  **Expected behaviour:** The cropper canvas changes size based on rotation

**Comment by ValentinH** [comment]
You could do a PR to add an option to deactivate this behaviour. If this option is enabled, then you should be able to always pass `0` to this function: https://github.com/ricardo-ch/react-easy-crop/blob/master/src/helpers.ts#L7

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉
