### ISSUE TITLE
Black background on transparent PNG

### ISSUE THREAD

**Issue by CristinaCST** [ricardo-ch/react-easy-crop#165]
Is there a way to replace the transparent background of PNGs with white? I couldn't find any. 

Thank you.

**Comment by CristinaCST** [comment]
You can close this. I managed to this by adding background to the Cropper.

**Comment by arminsalcin** [comment]
Can we keep the background of image transparent i don't want any background color, trying to make but not success any  help ?

**Comment by ValentinH** [comment]
Are you talking about the background when the image is shown in the cropper or once the new image is created?

**Comment by arminsalcin** [comment]
I'm talking when image is cropped example i want to crop some image that has transparent background, and when crop it i get black background, so how to keep it transparent after cropping?

**Comment by ValentinH** [comment]
I don't really know. You should check with the canvas API and then don't forget to export it to PNG (instead of JPG in the example).

**Comment by arminsalcin** [comment]
Okay i found it i didnt change export to "image/png" , thank you it works now !

**Comment by arminsalcin** [comment]
So if u want to automate this in the way u don't need to think about it next time we can extract the type from image meta ( I know this is not high security thing), but it's better then trying to find why it doesn't work so in your getCroppedImg() function add this somewhere on the top :
```const type = imageSrc.split(";")[0].split("/")[1];```
And when use it when u export your blob here :
```
 return new Promise((resolve) => {
    canvas.toBlob((file) => {
      resolve(file);
    }, `image/${type}`);
  });
```

**Comment by Dileepss** [comment]
How can I change the background color of the cropped image black to white

**Comment by ValentinH** [comment]
@Dileepss this should help you: https://github.com/ValentinH/react-easy-crop/issues/148#issuecomment-647388058

**Comment by Dileepss** [comment]
Thank you for such a speedy response.

**Comment by seachai** [comment]
> @ValentinH this should help you: https://github.com/ricardo-ch/react-easy-crop/issues/148#issuecomment-647388058

This returns a 404 url. Could you relink to another fix?

**Comment by ValentinH** [comment]
https://github.com/ValentinH/react-easy-crop/issues/148#issuecomment-647388058
