### ISSUE TITLE
Feature request!

### ISSUE THREAD

**Issue by skyylabz** [ricardo-ch/react-easy-crop#166]
- after user crops an image, is there a way to add a text box feature? So the user can write text over the image in different fonts and colors?

**Comment by ValentinH** [comment]
Yes, this is possible to do this in the canvas logic. You can add this text operation in the `cropImage` file in the example with the output.

**Comment by skyylabz** [comment]
So it would be the canvasUtils in the other version?

**Comment by skyylabz** [comment]
You wouldn't consider adding this would you? I'm not sure I know enough code to pull this off 💩

**Comment by ValentinH** [comment]
> So it would be the canvasUtils in the other version?

Yes indeed

I don't know how to do it either but I just know that this should be possible.

**Comment by ValentinH** [comment]
I'm closing this as this is not a feature request for the library itself.
