### ISSUE TITLE
Feature Request: Ability to hide the overflow area and use the parent container as restrictive bounds.

### ISSUE THREAD

**Issue by CorfitzMe** [ricardo-ch/react-easy-crop#167]
**- Please describe your use case from user journey point of view, e.g.:**
I would like to have a single elegant container where the user can position the image within. So when the user uploads an image, they will see pretty much exactly how the final result will be, and then they only have to position the image inside the container. 

![Screenshot 2020-08-15 at 07 50 05](https://user-images.githubusercontent.com/52371939/90306548-a882e000-dece-11ea-91ab-1a7c73eacbe8.png)

**- If you have ideas how to implement your new feature, please share!**
I have tried to assign the `cropSize` property, which somewhat solves the problem, though makes it more complicated to maintain a responsive environment, as the pixel values would have to be calculated and passed to the `Cropper` component. And if the user zooms out to Zoom 1, there is a lot of whitespace, despite `retrictedPosition` being set to `true`;

| ![ezgif-6-8fa2af1b5d83](https://user-images.githubusercontent.com/52371939/90306520-53df6500-dece-11ea-86ca-1bddf7fe1163.gif) | ![ezgif-6-ca2923290c55](https://user-images.githubusercontent.com/52371939/90306499-1084f680-dece-11ea-83a8-77cc56c6e4cd.gif)|
|---|---|

This package pretty much have all the logic ready, and I imagine that it is a matter of automatically calculate the`cropSize` property to be 100% width and height of parent, and then make sure, that `zoom` state at value `1` can't be smaller in height or width than the cropsize area _(Which I would expect should have been the matter anyway)_.

**- If you know any examples online that already implement such functionality, please share a link.**
Facebook does this. I like the simplicity in how you simply drag to decide what part you want shown, and then that's the data kept. I would just also like the ability to zoom and drag on the X-axis as well - which this package allows.

![ezgif-6-dc0a98770078](https://user-images.githubusercontent.com/52371939/90306445-905e9100-decd-11ea-95e3-03a25796a6bb.gif)

**Comment by ValentinH** [comment]
Thanks for the really clear issue. 👍 

Regarding `cropSize`, maybe we could support percentage values: if you pass `{ width: '100%', height: '100%' }`, then we take the size from the container size.

Regarding `zoom`, a value of 1 means that the image will fit the container in a "contain" mode. If you want it to cover the container entirely, you need to set the initial zoom and `minZoom` to a value higher than 1 (computed from container size and image ratio).

Here's an example sandbox that should match what you want: https://codesandbox.io/s/cocky-meitner-mlm8v

**Comment by CorfitzMe** [comment]
This is brilliant! It makes good sense - and thanks for the sandbox!

In order not to conflict in types for the `cropSize` maybe make it so, if the value is explicitly set to `cropSize={{height:0, width:0}}` or `cropSize={{height:-1, width:-1}}` it would interpret as 100%. Don't know how easy would be to implement.

Maybe we could add a prop called `matchParent` or similar,  that does this automatically (calculates the minZoom and sets the cropSize etc.) - should this be a more common desire. _(Probably even more complicated haha)_

**Comment by ValentinH** [comment]
I'd like to avoid adding extra props: the larger the API is, the more complicated it is to maintain a library.

With the example I provided, do you even need something new in the library?

If it can be achieved in user land, then it's better not to extend the library.

**Comment by CorfitzMe** [comment]
Sure - I mean. This would work and help me proceed. The 100% crop size might not be a bad idea to implement if it doesn’t require too much additional logic, but in terms of the prop, it was mainly a suggestion to facilitate the implementation. But I can definitely work with this as you have provided me with a decent solution. Much appreciated. 🍻

**Comment by ValentinH** [comment]
Handling the 100% case would not be too hard but it's still more logic to add.

If the example I provided fits your use case, I would stop here and not implement anything new. :)

**Comment by CorfitzMe** [comment]
Seems to work out quite fine.. Thanks!

```js
import React, { useState, useCallback, useEffect, useRef } from "react";
import Cropper from "react-easy-crop";
import styled from "styled-components";

const CropContainer = styled.div`
  position: absolute;
  top: 0;
  width: 100%;
  height: 100%;
  left: 0;
`;

const UploadMainMedia = () => {
  const path =
    "https://img.huffingtonpost.com/asset/5ab4d4ac2000007d06eb2c56.jpeg?cache=sih0jwle4e&ops=1910_1000";
  // Image cropper state
  const [crop, setCrop] = useState({
    x: 0,
    y: 0,
  });
  const container = useRef<HTMLDivElement | null>(null);
  const [size, setSize] = useState(300);
  const [zoom, setZoom] = useState(1);
  const [minZoom, setMinZoom] = useState(1);
  const [loaded, setLoaded] = useState(false);

  const onCropComplete = useCallback((croppedArea, croppedAreaPixels) => {
    console.log(croppedArea, croppedAreaPixels);
  }, []);

  useEffect(() => {
    setLoaded(false);
    const img = new Image();
    img.onload = () => {
      setZoom(img.width / img.height);
      setMinZoom(img.width / img.height);
      setLoaded(true);
    };
    img.src = path;
    return () => {};
  }, [path]);

  useEffect(() => {
    const updateSize = () => {
      if (container.current) {
        setSize(container.current.getBoundingClientRect().width);
      }
    };
    window.addEventListener("resize", updateSize);
    return () => {
      window.removeEventListener("resize", updateSize);
    };
  }, [container]);

  return (
    <CropContainer ref={container}>
      {loaded ? (
        <Cropper
          image={path}
          crop={crop}
          zoom={zoom}
          style={{ cropAreaStyle: { borderRadius: 10 } }}
          minZoom={minZoom}
          aspect={1}
          cropSize={{ height: size, width: size }}
          onCropChange={setCrop}
          onCropComplete={onCropComplete}
          onZoomChange={setZoom}
        />
      ) : (
        <div className="loading">Loading</div>
      )}
    </CropContainer>
  );
};

export default UploadMainMedia;

```

**Comment by ValentinH** [comment]
Can we close this issue?

**Comment by sebastian10c** [comment]
Man, I've spent hours trying to do this and got desperate enough to just go through all the closed issues and found this.
I'm sure there are more pressing issues to attend to, but if you could spare a moment, maybe there could be a demo of this somewhere in the documentation?
Also @imCorfitz example only works for horizontal images. I've fixed it by doing
```ts
setZoom(Math.max(img.width / img.height, img.height / img.width));
setMinZoom(Math.max(img.width / img.height, img.height / img.width));
```

**Comment by ValentinH** [comment]
@sebastian10c you are right! If you want, you could provide a codesandbox demoing what you did and I would be happy to add it to the README 🙂
