### ISSUE TITLE
When I fix croparea, the video is in the wrong position in firefox

### ISSUE THREAD

**Issue by coderyyx** [ricardo-ch/react-easy-crop#168]
## When I fix croparea, the video is in the wrong position in firefox

1、fix aspect and cropSize

https://codesandbox.io/s/react-easy-crop-for-videos-forked-tu6lk

**Comment by ValentinH** [comment]
I don't know what result you are trying to achieve, but you should not use aspect and cropSize together.

Most of the time, you should use aspect. Then for some advance use cases, you can use cropSize (without aspect).

**Comment by coderyyx** [comment]
@ValentinH The same code behaves differently in different browsers, when I only use cropSize, chrome and firefox. 
The first one is what I expect.

![image](https://user-images.githubusercontent.com/19465842/90350331-6644d480-e06f-11ea-8fb8-521c074f2d84.png)
![image](https://user-images.githubusercontent.com/19465842/90350347-7d83c200-e06f-11ea-844a-e5daa2d01d11.png)

**Comment by ValentinH** [comment]
This is odd. Do you have the same issue when only using the `aspect` prop?

**Comment by coderyyx** [comment]
@ValentinH I found the problem, the width and height of the video in firefox are wrong. It is related to onLoadedMetadata～
![image](https://user-images.githubusercontent.com/19465842/90372924-be95c980-e0a3-11ea-8a29-8fa14db29715.png)

**Comment by ValentinH** [comment]
Is this something to be fixed in the library or in the user-land code?

**Comment by coderyyx** [comment]
@ValentinH need to repair the library, I temporarily use onLoadedData.

**Comment by ValentinH** [comment]
Would you like to make a PR?

**Comment by ValentinH** [comment]
Could you please share more info on what needs to be fixed?

**Comment by Fivedark** [comment]
I have the same issue on Firefox, and it depends on the video file. 

Sadly I can't tell you, how to solve this, but I can tell you how to reproduce:

Open your video example in Firefox: https://codesandbox.io/s/react-easy-crop-for-videos-lfhme

And replace the video URL with: https://res.cloudinary.com/demo/video/upload/dog

**Comment by ValentinH** [comment]
Thanks for providing more examples (and an awesome dog video 😄)

**Comment by ValentinH** [comment]
This was fixed in v4.0.0. 🎉 

Thanks @trurl-master, this is the 3rd issue that you fixed with your PR 😄 🙇
