### ISSUE TITLE
Can i get cropped rect position in Float format

### ISSUE THREAD

**Issue by SamirNvi** [ricardo-ch/react-easy-crop#169]
Hi , 
Thanks again for this wonderful plugin.

I wanted to inquire that, is there a way that if i pass default cropped  rect the with decimal points and if user changes the cropped rect i should get rect in decimal points without rounding the values?

Is there a way or setting for this.

**Comment by ValentinH** [comment]
The cropped rect is returned in pixels, why do you need decimals?
If you really want accurate rect, you can get the percentage values with the second argument of `onCropComplete`.

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉
