### ISSUE TITLE
Ionic 5 & React: selection window is not displayed until window geometry changes

### ISSUE THREAD

**Issue by mutech** [ricardo-ch/react-easy-crop#170]
## Are you reporting a bug?

Using the latest version of Ionic and React, I have this example (basically your demo):
```ts
export const ImageCropPage: React.FC = (props) => {
  const [crop, setCrop] = useState({ x: 0, y: 0 });
  const [zoom, setZoom] = useState(1);
  const onCropComplete = useCallback((croppedArea, croppedAreaPixels) => {
    console.log(croppedArea, croppedAreaPixels);
  }, []);

  return (
    <IonPage>
      <IonContent>
        <div className="crop-main">
          <div className="crop-container">
            <Cropper
              image="assets/img/restaurant-header-example-1024x768.jpeg"
              crop={crop}
              zoom={zoom}
              aspect={16 / 9}
              onCropChange={setCrop}
              onCropComplete={onCropComplete}
              onZoomChange={setZoom}
            />
          </div>
        </div>
      </IonContent>
    </IonPage>
  );
};
```

- Provide the steps to reproduce the issue, e.g.:

  **Observed behaviour:** The cropper is outside the image

The problem is that the selection rectangle is not displayed (the image is displayed) until the window geometry changes (e.g. I resize the window or change orientation on a phone).

  **Expected behaviour:** The cropper stays within the image

I guess your component misses an event that you would receive in a plain react context. It seems to occur quite often than in Ionic some hooks do not get called at the right time or not at all.

**Comment by mutech** [comment]
I found the problem, in deed an Ionic life cyle issue. Annoying...

Here is a workaround:

```ts
class PatchedCropper extends Cropper {
  private isMediaLoaded: boolean = false;
  constructor(p: Props) {
    super(p);
    // patch to ensure the callback is only called once
    this.onMediaLoad = () => {
      this.computeSizes();
      this.emitCropData();
      this.setInitialCrop();

      if (!this.isMediaLoaded && this.props.onMediaLoaded) {
        this.isMediaLoaded = true;
        this.props.onMediaLoaded(this.mediaSize);
      }
    };
  }
  ionViewWillEnter() {
   // Earliest point (after all react events are done) when imageRef.complete is true
    if (this.imageRef && this.imageRef.complete) {
      this.onMediaLoad();
    }
  }
}
```

This needs to be wrapped in withIonLifeCycle like so:

```ts
export const IonicCropper = withIonLifeCycle(PatchedCropper);
```

Otherwise `ionViewWillEnter` will not fire.

Really nice code, btw. A pleasure to read!

**Comment by ValentinH** [comment]
Thanks for sharing your solution 🙂

**Comment by mutech** [comment]
You're very welcome, I really enjoyed going through your code and even more so the result. Very beautiful and amazingly small solution. Awesome job! Thank you guys!

**Comment by ValentinH** [comment]
Thank you for the really nice words, I'm happy that you enjoy this component. 🙂

**Comment by mauriceackel** [comment]
@ValentinH Any chance to get this information on the README? In something like a "Gotchas" section? Perhaps there are similar issues to this one, which would be very well suited for such a section.
I think it would be very helpful and save a lot of time (and headache 😅) for people with such issues.
