### ISSUE TITLE
Restrict image to cropping area

### ISSUE THREAD

**Issue by Eriickson** [ricardo-ch/react-easy-crop#171]
Hi, I have been using your component (Very good, by the way), but I have been limiting myself to using the rotation functionality, as my API does not crop the image when the image leaves the area, (you can see better in the illustration that I attach), I investigated everywhere but I do not see results, how could I do so that when I want to rotate the image, it does not exceed the crop box?
![image](https://user-images.githubusercontent.com/38663299/91908597-d2cbf000-ec79-11ea-84ec-90398e8fbe39.png)

**Comment by ValentinH** [comment]
If you don't want to have empty spaces when rotating the image, what behavior do you expect instead?

**Comment by Eriickson** [comment]
![image](https://user-images.githubusercontent.com/38663299/91914481-32c89380-ec86-11ea-8080-6720869f59e3.png)
Something like that! I once got that effect, but I don't remember if it was with your component and neither the method I used

**Comment by ValentinH** [comment]
Today, this is not possible to do this automatically.

We would need to add a new option in the library to prevent having empty spaces when the image is rotated. When this option is enabled, we would also need to restrict the crop position to prevent going outside the image. However, it would mean that some part of the  image would never be able to be selected (except by zooming).

I don't think that this is something trivial to implement. We need to change the rotation handling logic (translateSize function in the helpers file) to use this new option to change the computation. Would you like to work on a PR for this?

**Comment by Sommerfeld** [comment]
Hey, just wanted to add that this leads to issues when rotating by 90 degrees.

See:
- https://codesandbox.io/s/q8q1mnr01w
- Rotate by 90 degrees
- Show result
- This image has a 1px black "margin" on the right.

As we just need rotations in 90 degrees steps I will just implemented a workaround for us at the moment. I appreciate your work and I am really sorry that I am not able to work on a PR for it now.

**Comment by ValentinH** [comment]
https://twitter.com/JustePaulette/status/1331239422424190985?s=19

**Comment by ValentinH** [comment]
I just tried your example and didn't manage to reproduce. What browser are you using?

**Comment by Sommerfeld** [comment]
Chrome Version 87.0.4280.67 (Official Build) (x86_64)

![f556bdf6-209a-491d-9915-fcc9461a1fbc](https://user-images.githubusercontent.com/6570689/100363266-c4813c00-2ffc-11eb-8ba2-a8981f79640a.jpg)

**Comment by ValentinH** [comment]
Indeed, I could have the same issue on Firefox but not on Brave.It might simply come from a rounding error in the `cropImage.js` file of the demo.

**Comment by Sommerfeld** [comment]
That actually might be true for the example.

But I do have this type of issues in my project.

https://codesandbox.io/s/react-easy-crop-demo-with-cropped-output-forked-djt3c?file=/src/index.js

The width of the cropped area is 151px even so the image has a width of only 150px after rotating.

**Comment by ValentinH** [comment]
So then this sounds like a bug, the croppedArea should be correct in this condition. I think the rotation should be taken into account [here](https://github.com/ricardo-ch/react-easy-crop/blob/master/src/helpers.ts#L99) in order to switch width and height when rotation is 90 or 270°.

**Comment by ValentinH** [comment]
The issue mentioned by @Sommerfeld was fixed in v4.0.0.

The original feature request was not taken by anyone for more than a year. I'm closing this for now as this will not be implemented.
