### ISSUE TITLE
Let the user crop the image without specifying an aspect ratio

### ISSUE THREAD

**Issue by ahmedosama5200** [ricardo-ch/react-easy-crop#173]
I'd like the user to crop the image without being restricted by the aspect ratio, simply, I don't want a specific aspect ratio

**Comment by ValentinH** [comment]
Are you looking for a free form cropping tool like  https://github.com/DominicTobias/react-image-crop ?

**Comment by ahmedosama5200** [comment]
Exactly, I want something like that, But I love the way your cropper works, I mean, the box in the middle and the user moves the picture around it. He can zoom and rotate but he can not change the aspect ratio.
You could add arrows the sides of the crop box by which the user can change the size of the box
Do you have an intention to add a feature like that ?

**Comment by ValentinH** [comment]
I'm not sure that the UI could be pretty user friendly as the edges of the cropper are already fitting its parent. 

Also, the aspect is mandatory today (unless you provide a `cropSize` but this works differently). 

I don't think this would fit in this library. However, if you are motivated and still think it would be nice, feel free to provide a PR and we can see the result 🙂

**Comment by ahmedosama5200** [comment]
Okey, I will look into that
