### ISSUE TITLE
Setting cropSize doesn't effect returned cropped image size. 

### ISSUE THREAD

**Issue by tar-aldev** [ricardo-ch/react-easy-crop#176]
1.  Use Cropper component as follows
```
          <Cropper
              image={imageSrc}
              crop={crop}
              rotation={rotation}
              zoom={zoom}
              onCropChange={setCrop}
              onRotationChange={setRotation}
              onCropComplete={onCropComplete}
              onZoomChange={setZoom}
              cropSize={{ height: 300, width: 300 }}
            />
```
  2.  When uploading an image 1920X581px

  **Observed behaviour:**  the resulting image is 581x581;

  **Expected behaviour:**  the resulting image size should be 300x300

Code sandbox: https://codesandbox.io/s/react-easy-crop-custom-image-demo-forked-kxm4x?file=/src/index.js

**Comment by ValentinH** [comment]
Indeed, the `cropSize` prop is a bit misleading. It doesn't control the output size but only the size of the cropper on screen. As the image gets resized to fit its parent, selecting a 300px square on a large image will not output a 300px wide image.

As this component aims to provide a responsive image cropper, we actually cannot support what you are looking for.

**Comment by tar-aldev** [comment]
But I guess when you have a crop size e.g. 358 you expecting that resulting image would be the same size, no?

**Comment by ValentinH** [comment]
I just saw that you already tried it here:
![image](https://user-images.githubusercontent.com/2678610/92599463-96684780-f2aa-11ea-8b60-2be8a40f28ff.png)


I would have say to do this, so did it work? You might also need to adjust the x and y position to the new coordinates though.

**Comment by tar-aldev** [comment]
I tried it this way, but then it will just cut a part of cropped image, but it would be great if I coul somehoew just resize image to fixed 300x300 size, not cutting part of canvas.

**Comment by ValentinH** [comment]
I think the cropped image get cut because you need to adapt the `crop.x` and `crop.y` to fit the new scale.

For example, if the original crop width was 1000 and x was 500, if you want to result to be `300px` wide, then `x` should become `150`.

**Comment by ValentinH** [comment]
Did you solve your issue? Can I close it?

**Comment by SaajidJoosab** [comment]
Im running into this issue atm.. I've made it so the cropper scales to fit into a dialog given, and i've worked out the scale to scale it to. I'm just having some issues with having it ouput the cropped image at the right size.

**Comment by ogostos** [comment]
> I think the cropped image gets cut because you need to adapt the `crop.x` and `crop.y` to fit the new scale.
> 
> For example, if the original crop width was 1000 and x was 500, if you want to result to be `300px` wide, then `x` should become `150`.

Can you elaborate on that approach?

**Comment by ValentinH** [comment]
What you need to do is a scale conversion. Maybe this chart can help:
![image](https://user-images.githubusercontent.com/2678610/94568281-97b6df80-026c-11eb-8a9f-c556970261ea.png)

**Comment by carloslibardo** [comment]
I having same issue, i realted here: https://github.com/ricardo-ch/react-easy-crop/issues/124

I'm trying to fix that based on these comments, but without good results =/

**Comment by ValentinH** [comment]
I'm sorry I don't not have much time to help these days. The diagram above should lead you toward the solution.

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉

**Comment by irvanherz** [comment]
I've modified `getCroppedImg()` from example to output image in our desired size.
```js
export default async function getCroppedImg(imageSrc, pixelCrop, rotation = 0, resize) {
  const image = await createImage(imageSrc)
  const canvas = document.createElement('canvas')
  const ctx = canvas.getContext('2d')

  const maxSize = Math.max(image.width, image.height)
  const safeArea = 2 * ((maxSize / 2) * Math.sqrt(2))

  // set each dimensions to double largest dimension to allow for a safe area for the
  // image to rotate in without being clipped by canvas context
  canvas.width = safeArea
  canvas.height = safeArea

  // translate canvas context to a central location on image to allow rotating around the center.
  ctx.translate(safeArea / 2, safeArea / 2)
  ctx.rotate(getRadianAngle(rotation))

  ctx.translate(-safeArea / 2, -safeArea / 2)

  // draw rotated image and store data.
  ctx.drawImage(
    image,
    safeArea / 2 - image.width * 0.5,
    safeArea / 2 - image.height * 0.5
  )
  const data = ctx.getImageData(0, 0, safeArea, safeArea)

  // set canvas width to final desired crop size - this will clear existing context
  canvas.width = pixelCrop.width
  canvas.height = pixelCrop.height

  // paste generated rotate image with correct offsets for x,y crop values.
  ctx.putImageData(
    data,
    0 - safeArea / 2 + image.width * 0.5 - pixelCrop.x,
    0 - safeArea / 2 + image.height * 0.5 - pixelCrop.y
  )

  if (resize) {
    const oc = document.createElement('canvas')
    const octx = oc.getContext('2d');
    oc.width = resize.width
    oc.height = resize.height
    octx.drawImage(canvas, 0, 0, canvas.width, canvas.height, 0, 0, resize.width, resize.height);
    return oc.toDataURL('image/jpeg');
  } else {
    return canvas.toDataURL('image/jpeg');
  }
  // As a blob
  // return new Promise(resolve => {
  //     canvas.toBlob(file => {
  //         resolve(URL.createObjectURL(file))
  //     }, 'image/jpeg')
  // })
}
```
