### ISSUE TITLE
I`ve got infinite loop after upload image in cropper

### ISSUE THREAD

**Issue by johnylikesjuice** [ricardo-ch/react-easy-crop#185]
`  <Cropper
          minZoom={1}
          image={cropperPreview}
          showGrid={false}
          crop={crop}
          zoom={zoom as number}
          aspect={1}
          cropSize={{ width: +width, height: +height }}
          restrictPosition={false}
          onCropChange={setCrop}
          onCropComplete={(croppedArea, croppedAreaPixels) => {
            onCropComplete({
              croppedAreaPixels,
              cropperPreview,
              currentFormat: currentTab.format,
              showCropper,
              zoom,
            });
          }}
        />`

Hi ! I'm using your component, everything is fine, but after updates some issues happens.
This is my component, and I've got an infinite loop after image was uploaded in the Cropper.
This is how errors  looks like :
<img width="956" alt="Screenshot 2020-10-21 at 18 31 39" src="https://user-images.githubusercontent.com/44061507/96742585-c0457b80-13cb-11eb-9412-d9da4134d291.png">

<img width="1235" alt="Screenshot 2020-10-21 at 18 16 56" src="https://user-images.githubusercontent.com/44061507/96742013-19f97600-13cb-11eb-8c5c-f05e31154784.png">

Seems to be, this is a peace of code from new updates
https://github.com/ricardo-ch/react-easy-crop/commit/b8ce61753a09e12210c0f07467d139ea781d17d4

UPD: this happens not every time, so I'm not sure that can reproduce this bug in sandbox, maybe you have thoughts what can cause problems like this ?

**Comment by ValentinH** [comment]
I think this comes from your conversion made with `+width`, you should not do this.

**Comment by johnylikesjuice** [comment]
`+width` is converting string into number, but I'll dig deep in it. Thanks

**Comment by ValentinH** [comment]
Yes but it might be the issue as the cropSize seems to be changing at each render.

**Comment by johnylikesjuice** [comment]
yeap, the main idea was correct. Thanks @ValentinH
