### ISSUE TITLE
How to change the cropped images background color?

### ISSUE THREAD

**Issue by Testarrosa** [ricardo-ch/react-easy-crop#187]
The background color of cropped image is black when I set the minZoom props to the 0.2,I want to know how to change the background color?

**Comment by ValentinH** [comment]
Do you mean the background in the UI or the background of the output image?
I think that both are actually covered in existing closed issues.

**Comment by Testarrosa** [comment]
Thanks,I mean the background of the output image ,I can't find the answer from existing closed issues.

**Comment by ValentinH** [comment]
See https://github.com/ricardo-ch/react-easy-crop/issues/148
