### ISSUE TITLE
Unable to set initial crop state of cropped, rotated image.

### ISSUE THREAD

**Issue by thilini1986** [ricardo-ch/react-easy-crop#189]
**Describe the bug**
Setting initial crop state when a image is rotated is not possible with "initialCroppedAreaPixels" or "crop"

**To Reproduce**
Steps to reproduce the behaviour:
1. Set a image on cropper
2. Rotate image,  change crop position
3. On crop complete set initialCroppedAreaPixels to local storage
4. On reload the page the initialCroppedAreaPixels from local storage
5. Reload the page, image will not be on exact position as previous

In this example I am always setting rotation o 90 degree.

**Expected behavior**
On reloading page image should be rotated and crop area should be on same passion as before 

- Please create a CodeSandbox that demonstrates your issue. You can fork the Basic example: https://codesandbox.io/s/react-easy-crop-example-with-local-storage-sync-forked-4no99?file=/src/index.js

**Comment by ValentinH** [comment]
Hello, indeed this is a bug. The rotation was added after the initial crop logic and the logic was not updated as you can see on this line: https://github.com/ricardo-ch/react-easy-crop/blob/master/src/index.tsx#L196

The function should also take the rotation as input and use it to compute the crop value.

Would you like to work on a PR to fix this?

**Comment by b-des** [comment]
Hi @ValentinH, @thilini1986,
I've fixed the issue and now it work properly. I added new one prop ```initialRotation``` and it can be used to apply previous rotation. 
E.g. after image roatated and crop position changed save both parameters to local storage, then use it to set props ```initialCroppedAreaPixels``` and ```initialRotation``` and it should wortk well. 

If it's what you looked for I can create PR.

@ValentinH, also added possibility to correct dragging image when the cropper is using with rotated parent container, which has rotate parameter in transform style - ```transform: rotate(65deg)```

**Comment by ValentinH** [comment]
Thanks! A PR would be very welcomed indeed :)

**Comment by ValentinH** [comment]
After trying it again, I actually noticed that you should also store the `rotation` in the local storage. Doing this works fine: codesandbox.io/s/react-easy-crop-demo-with-local-storage-73u6i?file=/src/index.js

@thilini1986 please reopen if this is not matching your issue.
