### ISSUE TITLE
react-native support? 

### ISSUE THREAD

**Issue by 3GOMESz** [ricardo-ch/react-easy-crop#191]
...

**Comment by ValentinH** [comment]
No

**Comment by 3GOMESz** [comment]
No plans to create another version of this project, right?

**Comment by ValentinH** [comment]
Not at the moment. However, making a react native version should not be impossible, a big part of the logic could be reused. What needs to be rewritten is all the event handling logic, image measurements and the styling as they are made for the DOM.

**Comment by 3GOMESz** [comment]
It would be a great choice to create an image crop project for react-native. The current alternatives have not been very effective, and the few that work limit customization using a limited external api.
