### ISSUE TITLE
Zoom works very slow on Firefox

### ISSUE THREAD

**Issue by mndzielski** [ricardo-ch/react-easy-crop#192]
Zoom using mouse scroll is much slower in Firefox than in Google Chrome.

1. Open https://codesandbox.io/s/v69ly910ql in Chrome and Firefox
2. Zoom image in Chrome and Firefox using mouse scroll

**Expected behavior**
The speed of zoom should be similar or the same.

Example: https://codesandbox.io/s/react-easy-crop-v69ly910ql.

**Comment by ValentinH** [comment]
Thanks for the report and sorry for the delay for the answer.

You are right, this looks wrong. 

We rely on the `e.deltaY` (https://github.com/ricardo-ch/react-easy-crop/blob/master/src/index.tsx#L354) property which might have different value across browsers.

Would you like to investigate what we could do to align the behavior?

**Comment by ValentinH** [comment]
Fixed with version 3.3.1.
