### ISSUE TITLE
Flip Image Feature

### ISSUE THREAD

**Issue by jobingn** [ricardo-ch/react-easy-crop#193]
I have seen flip as in props to flip the image using values like this 

const [flip, setFlip] = useState({horizontal: true, vertical: false})

I tried and it's not working. but in this demo, it's working fine. 

https://ricardo-ch.github.io/react-easy-crop/

Please add this feature or if any additional config I have to do to make it work. Please let me know

**Comment by ValentinH** [comment]
The demo website is also open-source so you can check how it's done: https://github.com/ricardo-ch/react-easy-crop/blob/master/docs/src/components/Demo/index.tsx#L66

🙂

**Comment by jobingn** [comment]
Thanks
🙂

**Comment by ValentinH** [comment]
Can this issue be closed?
