### ISSUE TITLE
cropped GIF not animated

### ISSUE THREAD

**Issue by kafinsalim** [ricardo-ch/react-easy-crop#194]
**Describe the bug**
It says Supports GIF images format. But I only got 1 frame of the image after cropping a GIF

**To Reproduce**
1. Open https://ricardo-ch.github.io/react-easy-crop/
2. Go to codesandboxes example and Select with image selected by user
3. Choose a gif file
4. The result only had the first frame of the cropped gif

**Expected behavior**
The cropped gif image is animated

Also is there a way to support GIF cropping and persist all frame?

**Comment by ValentinH** [comment]
The library itself is not responsible for actually cropping the image and showing the result. The cropping logic is provided in the examples for simple images just for documentation purpose.

I don't even know if cropping a GIF inside the browser is possible to be honest.

**Comment by kafinsalim** [comment]
I was searching for a react image cropper that can crop GIF image and persist animation, most of the library I found not able to crop a GIF and persist the animation.
I thought this one can do it because in the readme it says: Supports any images format (JPEG, PNG, **even GIF**) as url or base 64 string. I'll close this, thanks for responding ☺️ !
