### ISSUE TITLE
Not working correctly in iframe

### ISSUE THREAD

**Issue by prztrz** [ricardo-ch/react-easy-crop#195]
Hi,

I wanted to use this component in widget application which is rendered on iframe, however dragging events do not work properly (well they do not work at all - dragging inside Cropper is not possible). During debugging i learned that component adds events directly to the document. Documment doesnt listen to events dispatched in iframe which is possible source of the bug.

Would it be possible to add  `document` prop to  provide custom document instance do react-easy-crop component ot fix this?

**Comment by ValentinH** [comment]
Hey

Could you create a codesandbox showing the issue please? It will be easier to understand the behaviour and come up with a potential solution.

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉
