### ISSUE TITLE
Feature Request: Make mouse-wheel zoom-speed configurable

### ISSUE THREAD

**Issue by TheRealSlapshot** [ricardo-ch/react-easy-crop#20]
We would like to adjust the speed with which a mouse-wheel-turn zooms in or out of the image.

Maybe the value would be a specific step-value, by which the zoom will be increased/decreased or speed-factor, by which the mouse-wheel-delta will be multiplied, with 1 being the default and current behaviour.

Libraries implementing such a feature:
- https://github.com/woutervh-/react-pan-and-zoom-hoc (scaleFactor)
- https://github.com/timmywil/panzoom (increment)

**Comment by ValentinH** [comment]
Indeed this is a good idea. Would you like to submit a PR for this?
Regarding the choice between `increment` and `scaleFactor` I don't really know. The current value was chosen by "trying" different values and picking one that looked good to me. ^^

**Comment by TheRealSlapshot** [comment]
First of all I want to wish you a happy new year.
I will have a look on this, but can make no commitments on how fast I will be.
