### ISSUE TITLE
issue with ios (Camera picture)

### ISSUE THREAD

**Issue by djsanj007** [ricardo-ch/react-easy-crop#201]
**Describe the bug**
Saving black image When using user upload option & use camera picture, the image loads in crop area, but return the black image

**To Reproduce**
1. Go to 'https://codesandbox.io/s/y09komm059' from the iOS browser
2. Click on 'Choose file & select 'take photo' option'
3. Click picture & select Show result (Don't need to zoom or rotate)
4. Click show result

**Expected behavior**
It should show the cropped image but showing black image(Only iOS camera option)
![IMG_A9C35AC798CF-1](https://user-images.githubusercontent.com/739586/103402036-5850a580-4b71-11eb-99f8-945975ca31a4.jpeg)

**Comment by ValentinH** [comment]
This is a known issue on iOS, you can check the existing issues to find the solution.

**Comment by ValentinH** [comment]
Closing as it's a duplicate.

**Comment by djsanj007** [comment]
@ValentinH  can you link it to the original bug

**Comment by ValentinH** [comment]
Please use the issues search feature using "ios" or "black" and you will find them.
