### ISSUE TITLE
croppedAreaPixels negative values once using rotation

### ISSUE THREAD

**Issue by ofekudi** [ricardo-ch/react-easy-crop#203]
**Describe the bug**
Once using rotation, for example 90/270 degrees, `croppedAreaPixels` argument contains invalid values for `x` and `y` - for example the top-left corner is not the origin (0, 0) and `y` contains negative values.

How can I calculate the correct x, y values once using rotation?

**To Reproduce**
1. Set `rotation` to 90 degrees
2. Drag the photo to the top-left corner
3. Log `croppedAreaPixels` in `onCropComplete`
4. See invalid values

**Expected behavior**
The top-left corner should be (x=0, y=0)

Use this fork in order to reproduce the issue:
https://codesandbox.io/s/react-easy-crop-demo-with-cropped-output-forked-lmxl0?file=/src/index.js

**Comment by ValentinH** [comment]
If you use the example you linked, and display the result using the "Show result" button, you can see that the scenario you described actually works.

The thing is that you need to first rotate the image from the center, then translate it. This is how the default transformation works in CSS.

You can see the logic for compute the result here: https://codesandbox.io/s/react-easy-crop-demo-with-cropped-output-forked-lmxl0?file=/src/cropImage.js:768-777

**Comment by ofekudi** [comment]
What I mean is that the origin's coordinates are (x=455, y=-454), and I expected them to be (x=0, y=0):
![image](https://user-images.githubusercontent.com/76157707/104929835-14510380-59ad-11eb-9989-f27a6449c627.png)

I don't need to display the image myself, but to give its cropping pixels to a 3rd party app.
So is my only option is to compute the correct x and y values myself the same way you've done in the example?
Thanks :)

**Comment by ValentinH** [comment]
Does the third party app handles the rotation?

**Comment by ofekudi** [comment]
Yes, it receives { rotation, x, y, width, height }. Afterwards, it first rotates the photo and then crops it according to the coordinates.
It works fine with 0/180 degrees, as the top-left corner is (x=0, y=0), but unfortunately that's not the case with 90/270 degrees.
Let me know if I'm not clear enough

**Comment by ValentinH** [comment]
Yes I understand your point. You might be able to use a function similar to [this one](https://github.com/ricardo-ch/react-easy-crop/blob/master/src/helpers.ts#L213) to rotate the coordinates. I tried it quickly and it doesn't seem to be easy though.

It requires some math to rotate the coordinates properly based on the image size, the current position and the rotation.

**Comment by ofekudi** [comment]
Hey Valentin. 
My current solution for calculating the correct coordinate in relation to the top-left corner is using the `crop` param.
I appreciate your help and thanks for your time!

**Comment by ValentinH** [comment]
I'm glad you found a solution!
Would you like to share what you did as a reference for future readers of this issue? 🙂

**Comment by ofekudi** [comment]
It's a very good idea, I hope it will help others.

Some notes:
* `mediaSize` - the same that is received in `onMediaLoaded` callback
* `crop` - the same that is received in `onCropChange` callback
* `cropSize` - in my case is a square, you may want to change it if you're using rectangle crop size (and also flip dimensions if image is rotated)

```  
  function shouldFlipImageDimensions (rotation) {
    const rotationDegrees = Math.abs(rotation)
    return rotationDegrees % 360 === 90 || rotationDegrees % 360 === 270
  }

  function transformCenterToOrigin () {
    let { width, height, naturalWidth, naturalHeight } = mediaSize

    // Switch image dimensions in case of rotation
    if (shouldFlipImageDimensions(rotation)) {
      ;[width, height] = [height, width]
      ;[naturalWidth, naturalHeight] = [naturalHeight, naturalWidth]
    }
    // Cropper's image width and height are multiplied by the current zoom - for
    // example if the zoom is 2, the image sizes should as well multiple by 2
    width *= currentZoom
    height *= currentZoom

    // Convert distance from the center to distance from the origin
    let x = (width / 2) - crop.x - (cropSize / 2)
    let y = (height / 2) - crop.y - (cropSize / 2)
    // Calculate coordinate values in proportion to the natural image size
    x *= naturalWidth / width
    y *= naturalHeight / height
    return { x: Math.round(x), y: Math.round(y) }
  }
```

**Comment by ValentinH** [comment]
Thanks for sharing this!
Can I proceed with closing this issue now?

**Comment by ofekudi** [comment]
Of course 😊
