### ISSUE TITLE
Cropped image is getting black full image in iphone mobiles

### ISSUE THREAD

**Issue by vinodtana1** [ricardo-ch/react-easy-crop#207]
**Describe the bug**

**To Reproduce**

**Expected behavior**

- Please create a CodeSandbox that demonstrates your issue. You can fork the Basic example: https://codesandbox.io/s/react-easy-crop-v69ly910ql.

**Comment by vinodtana1** [comment]
same image cropping is working fine in chrome and all devices 
but in iphone mobiles cropped image is getting black color

**Comment by ValentinH** [comment]
Duplicate of many issues regarding ios and black output. Please use the search tool.
