### ISSUE TITLE
Trying to the implement the mouse event's with Button for Accessibility compliance

### ISSUE THREAD

**Issue by AnilGayakwad** [ricardo-ch/react-easy-crop#208]
**Is your feature request related to a problem? Please describe.**
Want to implement all mouse event with button click on the screen for Accessibility compliance, 
The Zoom in an Zoom out works as expected, with below code. 
 `setZoom((zoomIn < 1) ? 1 : zoomIn);`
 `setZoom((zoomOut > 3) ? 3 : zoomOut); ` 
 
 The Arrow key work's as well, but the image is going out of its restricted boundary, and on click of the image with mouse the image returns back to it boundary. 
 `const currentYPosition = crop.y;
    const currentXPosition = crop.x;
    const movePxAtATime = 10;
    ` 
 `setCrop({ x: currentXPosition, y: (currentYPosition + movePxAtATime) });` <-- Move Down 
 `setCrop({ x: currentXPosition, y: (currentYPosition - movePxAtATime) });` <-- Move Up
 `setCrop({ x: (currentXPosition - movePxAtATime), y: currentYPosition });` <-- Move Left 
 `setCrop({ x: (currentXPosition + movePxAtATime), y: currentYPosition});` <-- Move Right
 
 How to do that, with Button click's, Want to disable the button as soon a guest hit the boundary.   
![1](https://user-images.githubusercontent.com/9487037/107447225-ab6d2f00-6b05-11eb-82c7-da6b626693ca.png)

![2](https://user-images.githubusercontent.com/9487037/107447226-ac05c580-6b05-11eb-8938-4ec79bdd9586.png)

**Comment by ValentinH** [comment]
Hello, I think this is a valid use case. One solution is see would be to provide a prop that would accept a function called every time the crop position changes. In this function you would be able to transform the position and return a new one.
Then if we export our internal `restrictPosition`, you  would be able to call it yourself in this callback prop.

I need to think more about it to find the best solution.

**Comment by ValentinH** [comment]
I'm sorry to say to I don't have much time to allocate for this at the moment. Do you still need a solution or did you find a workaround?

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉
