### ISSUE TITLE
How to upload as file to server

### ISSUE THREAD

**Issue by raihan-muhammad** [ricardo-ch/react-easy-crop#209]
Hi, i am having trouble uploading the cropped image file to the server. Because before I uploaded it as a file but when using this library it is in the form of a blob or base64 string. So my backend validation can't process it to storage. Please give me a solution. Thank you :(

**Comment by ValentinH** [comment]
You either have to adopt your backend to handle a base64 string or convert it to a file on the front-end before sending it. I don't know how to do this but there are probably existing libraries or tutorials to do this.

I'm closing this issue as this is not directly related to this library.

**Comment by akshy78695** [comment]
Here is how i did the upload part

first when you get cropped image change the return part with following
```
// As a blob
  return new Promise((resolve, reject) => {
    canvas.toBlob(
      (file) => {
        resolve(file);
        // resolve(URL.createObjectURL(file));
      },
      "image/jpg",
      1.0
    );
  });
```

Save above file in state (for e.g. in croppedImage)



Now when uploading 
```
function uploadImage(){
let image = new File([croppedImage], 'name');

const formData = new FormData();
formData.append("file", image, image.name);

...
}
```

Note: if you also want to result of cropped image set another state for it and set it to 
```
(URL.createObjectURL(resultYouGetFrom_getCroppedImg_func))
```
