### ISSUE TITLE
The library does not seem to support HEIC format

### ISSUE THREAD

**Issue by temurih** [ricardo-ch/react-easy-crop#210]
I am just curious to know what I can do in order to support HEIC format picture. (iPhone images)

**Comment by ValentinH** [comment]
I'm not sure what the limitation is because the library is simply using an `<img />` tag 🤔

**Comment by temurih** [comment]
@ValentinH I get a blank canvas if I upload `HEIC`. It might be something I am doing wrong

**Comment by temurih** [comment]
@ValentinH let me see if I can reproduce in Sandbox

**Comment by ValentinH** [comment]
Ah is it an issue with cropper component or the code to generate the cropped image?

**Comment by temurih** [comment]
@ValentinH yes!

**Comment by temurih** [comment]
@ValentinH The cropper component,

```
<Cropper
          image="cannot-send-heic-image-here-otherwise-it-returns-blank"
          crop={crop}
          zoom={zoom}
          aspect={4 / 3}
          onCropChange={setCrop}
          onCropComplete={onCropComplete}
          onZoomChange={setZoom}
          initialCroppedAreaPixels={initialCroppedAreaPixels}
/>
```

**Comment by temurih** [comment]
Try toggling between `Line 34 and 35` of `index.js`.

https://codesandbox.io/s/react-easy-crop-example-with-local-storage-sync-forked-zbf80?file=/src/index.js

**Comment by ValentinH** [comment]
This is weird because here how it's used: https://github.com/ricardo-ch/react-easy-crop/blob/main/src/index.tsx#L509

Does displaying a heic image works with a simple img tag?

**Comment by temurih** [comment]
@ValentinH Good question, I am not too sure. I have to try it.

**Comment by temurih** [comment]
I am working with `HEIC` first time myself

**Comment by temurih** [comment]
@ValentinH It does not seem to work with `<img />`. Try toggling between `Line 10 and 11` of `JS` section

**Comment by temurih** [comment]
@ValentinH Unfortunately none of the browsers support `HEIC`. I hate when companies try to re-invent the wheel. Everyone is happy with the image formats we already had, but Apple had to add their own thing!

https://caniuse.com/?search=heif

**Comment by ValentinH** [comment]
Yes I agree. 😑

As this is a platform limitation, I'm closing this issue.
