### ISSUE TITLE
Change selection area

### ISSUE THREAD

**Issue by Aichnerc** [ricardo-ch/react-easy-crop#217]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to change the zone manually.

|Current|Expectations|
|-|-|
|Variable greyed out area|Fixed greyed out area| 
| ![image](https://user-images.githubusercontent.com/21159914/110940194-cd411800-8336-11eb-82ab-9b5f63e06275.png) | ![test](https://user-images.githubusercontent.com/21159914/110940588-70922d00-8337-11eb-8b6c-5e57e4a4ac10.jpg) |

This is important because I for instance use it for a configuration system where the dimensions of the visible area are fixed and can not change on zoom, rotation and/or other parameters. They need to stay an exact amount of pixels or % from the edge.

**Describe the solution you'd like**
Being able to manually set the greyed out zone. No matter the aspect ratio of the image.

**Comment by ValentinH** [comment]
The philosophy of this library is to be responsive. For this reason, everything is based on aspect of the result image and not in pixels.

You might be able to use the `cropSize` to manually set the exact size of the zone, but you'll have to compute it based on the original image size and will lose all automatic responsiveness.

**Comment by Aichnerc** [comment]
Thanks for your quick response.
I have added a fixed crop size in **prozent** or **pixels**.

This is the error I get when I try to zoom or rotate / perform any action on it.
`index.js:1 TypeError: Failed to execute 'putImageData' on 'CanvasRenderingContext2D': Value is not of type 'long'.`

**Comment by Aichnerc** [comment]
Update:
The error was created by showing the cropped image.
I have used a string instead of the number as input for `cropSize` `height  and `width`.

**The issue has been resolved.**

**Comment by Aichnerc** [comment]
I have achieved what I wanted using a ReactJS reference and its `clientWidth` and `clientHeight`.

```
cropSize={{
  width: this.containerRef.current
    ? this.containerRef.current.clientWidth * 0.95
    : 200,
  height: this.containerRef.current
    ? this.containerRef.current.clientHeight * 0.95
    : 200,
}}
```

**Comment by ValentinH** [comment]
This is cool that you found a working solution for your issue and thanks for sharing it here 🙂
