### ISSUE TITLE
Support custom grids

### ISSUE THREAD

**Issue by brooks42** [ricardo-ch/react-easy-crop#219]
**Is your feature request related to a problem? Please describe.**

Nope, just a requirement from an employer.

**Describe the solution you'd like**

I'd like to be able to set a `grid` or `gridImage` prop, pass an SVG(?) and have that show as the grid instead of the 3x3 box.

**Describe alternatives you've considered**

I've tried to just z-index my way into having a grid SVG on top and setting `showGrid` in the lib to false. No luck yet, but I think I'll get it eventually. Would be much easier to just set a `grid` prop.

**Additional context**

I'm not sure how to go about implementing the feature yet since I'm still relatively new to JS, but going through the source a bit I don't _think_ it's too complicated? Hopefully I don't eat those words. :)

**Comment by ValentinH** [comment]
I was actually going to suggest to disable the default grid and add your own. As the parent container is relative, you should be able to position your custom grid with `position: absolute`.

What was the issue when trying this approach?

**Comment by brooks42** [comment]
The issue I'm facing is that I need the custom grid to match to the crop area box (so the user can compare the grid to the final cropped image). So far I've been unable to figure out how get the size of that box to resize my custom grid -- or tie my custom grid to the same component as the box so it's the same size. Any insights?

**Comment by ValentinH** [comment]
Using the `classes` property, you could set the `cropAreaClassName` class and use `background` to add your SVG grid I guess.

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉
