### ISSUE TITLE
Feature Request: Crop 2 images(background-image and image) into a single output image.

### ISSUE THREAD

**Issue by svenkatesh-nyros** [ricardo-ch/react-easy-crop#22]
Is it possible to provide the source image in a existing background image to crop them into single image using this package.
following is the example working urls for making this feature.

http://subinsb.com/create-profile-picture-framer-web-app/

Git url: https://github.com/subins2000/profile-picture-framer

can this feature implemented in your package ?

**Comment by ValentinH** [comment]
Yes it should be possible since the background image IS an image. Either it's a link to a file or a dataURL, this package supports them.

**Comment by ValentinH** [comment]
Closing as there was no answer for more than 10 days. Comment to re-open 😉
