### ISSUE TITLE
Passing image via URL.createObjectURL causes infinite rerendering

### ISSUE THREAD

**Issue by endrits079** [ricardo-ch/react-easy-crop#231]
**Describe the bug**
When I pass the image as {URL.createObjectURL(imgFile)} instead of image="some/path/image.jpg" it causes an infinite 
**To Reproduce**
1. Upload an image via input type file and save it on a state
2. Pass the image to the <Cropper image={URL.createObjectURL(imageSavedOnState)} .../>

**Expected behavior**
Image uploads and doesn't cause infinite rerendering

- https://codesandbox.io/s/laughing-agnesi-xxgsm?file=/src/index.js

**Comment by ValentinH** [comment]
This is because the reference returned by `URL.createObjectURL(imgFile)` will be new at each render call. To avoid the infinite loop, you need to wrap it in `useMemo` to get a stable reference.

**Comment by victorbyttebier** [comment]
`useMemo` did not work for a stable reference. Canceling the event solved it, i found the bug today when uploading images with a bigger file size.

**Comment by ValentinH** [comment]
Thanks
