### ISSUE TITLE
When transform everything stops working (for example, zoom doesnt work)

### ISSUE THREAD

**Issue by santialbornoz1** [ricardo-ch/react-easy-crop#232]
I started working with react-easy-crop and with zoom and rotate works fine. The problem is when i try to use transform too. Zoom and rotate doesnt not work more.

**To Reproduce**
Use Cropper without transform:
![WhatsApp Image 2021-04-05 at 11 33 43](https://user-images.githubusercontent.com/51669298/113585872-2e40d080-9603-11eb-86aa-209091051458.jpeg)
Until there everything works fine.

But, when i add transform prop to Cropper component, zoom and rotation doesnt work more.
![WhatsApp Image 2021-04-05 at 11 35 50](https://user-images.githubusercontent.com/51669298/113586001-56c8ca80-9603-11eb-9b99-d44029070de0.jpeg)
I need all of this features because i have an image editor (custom covers web page):
![WhatsApp Image 2021-04-05 at 11 38 15](https://user-images.githubusercontent.com/51669298/113586137-85df3c00-9603-11eb-8fb6-bae0c254bb3a.jpeg)

**Comment by ValentinH** [comment]
What value do you pass to the transform property? As this is the property used to apply the zoom and rotation, you need to apply them as well.

See this part of the doc:
![Screenshot_20210405-225230](https://user-images.githubusercontent.com/2678610/113625817-b229a580-9661-11eb-8eb1-7b46712a2b35.jpg)

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉
