### ISSUE TITLE
Allow cropper to fill width/height of the space

### ISSUE THREAD

**Issue by james2406** [ricardo-ch/react-easy-crop#233]
**Describe the solution you'd like**
I would like to show the cropped view instead of the image + cropped view. 

**Describe alternatives you've considered**
I have thought about scaling the cropped view myself with a transform however, the scroll speed becomes too fast.

**Additional context**

This is what my UI looks like right now:
<img width="768" alt="Screenshot 2021-04-10 at 12 19 25" src="https://user-images.githubusercontent.com/10858584/114268254-1b117480-99f8-11eb-8863-c77246ec6340.png">

This is what I'm hoping to achieve
<img width="768" alt="Screenshot 2021-04-10 at 12 20 20" src="https://user-images.githubusercontent.com/10858584/114268260-1ea4fb80-99f8-11eb-9cc7-711b65a50485.png">

**Comment by ValentinH** [comment]
Could you please share a codesandbox of your example so that I can try to find a solution?

**Comment by james2406** [comment]
Sure. Here's an example of how I was using transform to scale up the whole Cropper component to hide the background https://codesandbox.io/s/nervous-dubinsky-hwn3g?file=/src/styles.css

**Comment by ValentinH** [comment]
Indeed using the transform is hacky and will lead to other issues. I was more referring to showing an example of the UI shared in your screenshots.

After seeing this issue again, it reminds me of #55 .

**Comment by james2406** [comment]
Yes, that looks like a really similar request.

I put together another sandbox that has the same setup as my original screenshots https://codesandbox.io/s/elegant-rhodes-qb38y?file=/src/App.js. I'm trying to fit the cropped image inside the dotted lines.

**Comment by ValentinH** [comment]
Thanks for taking the time to create the sandbox and sorry for the delay to answer (I'm currently busy with other kinds of projects 🍼👶).

I think this is a valid use case and we should support this with a property that would allow defining how the crop area adjust to the parent container. I don't have a name in mind but the value could be "fit" (today's behaviour where we show the whole image on start) and "cover" where we fill the horizontal space.

I'll not have time to work on this in the coming days unfortunately but I'm open to review a PR for this.

**Comment by ValentinH** [comment]
Now that I'm back on a computer, I have good news for you @james2406: you can already achieved what you want by overriding the image styles: https://codesandbox.io/s/ecstatic-poincare-cb65x
![image](https://user-images.githubusercontent.com/2678610/115257088-12274e00-a130-11eb-849f-96edb8c1ba1d.png)

After playing a bit with it, it seems to match your needs.

I think this could still be added as an option to the library, but I have to think about what could be the best API for this. 🙂

**Comment by ValentinH** [comment]
@james2406 could you please have a look at https://github.com/ricardo-ch/react-easy-crop/pull/236 to see if it matches your needs?

**Comment by simonezuccala** [comment]
@ValentinH not OP, but I had the same needs and the changes you made in #236 worked for me.

**Comment by ValentinH** [comment]
Thanks @simonezuccala , I actually forgot that this PR wasn't merged! ^^
I'll merge it soon then.

**Comment by simonezuccala** [comment]
@ValentinH great, thank you! 😄

**Comment by ValentinH** [comment]
Released the new `objectFit` with [v3.4.0](https://github.com/ricardo-ch/react-easy-crop/releases/tag/v3.4.0) 🎉
