### ISSUE TITLE
Changing the background-color of the container.

### ISSUE THREAD

**Issue by Pranav2612000** [ricardo-ch/react-easy-crop#239]
Is it currently possible to change the background color of the container?
This is how it currently looks - 
![image](https://user-images.githubusercontent.com/20909078/115814678-2bbbe480-a413-11eb-8ac6-fa7153b0dc07.png)
I'll like to change the grayish background surrounding the image to be clear white. Tried changing the css to take white as the background color, but that doesn't solve the problem. 

My guess is some sort of opacity or something is applied to the image, but I was unable to find it.

Here's what happens if I set the background color to red-
![image](https://user-images.githubusercontent.com/20909078/115814626-1050d980-a413-11eb-9784-c0f64c23af88.png)

Also, Thank you for this amazing package.

**Comment by Pranav2612000** [comment]
Oh. Figured out the transparency was due to the crop container grid. Managed to solve it by passing 
```css
.crop-area {
	box-shadow:unset !important;
}
```
to the crop container styles.

Is there a better way to do this, withount needing !important

**Comment by ValentinH** [comment]
Indeed you need to unset  the `box-shadow`.
You have a css order issue and you can fix it by [opting-out of the automatic style injection](https://github.com/ricardo-ch/react-easy-crop#styles).

**Comment by Pranav2612000** [comment]
Sure. Thanks a lot @ValentinH
