### ISSUE TITLE
Is there any way to get cropped image in background

### ISSUE THREAD

**Issue by HarishReddyCH** [ricardo-ch/react-easy-crop#241]
**Describe the bug**
Is there any way to get cropped images without using Cropper component

**Expected behavior**
I dont want to show Cropper in UI, just wanna get cropped image in background

**Comment by ValentinH** [comment]
The logic the actually crop the images is not in this repository but only in the codesandbox examples. You can copy the code from there.

**Comment by HarishReddyCH** [comment]
function getCroppedImg(imageSrc, **pixelCrop**, rotation = 0) {
....
}

This one right ?
But, here we have to pass **pixelCrop** eg: {width: 1000, height: 1000, x: 454, y: 0}   this I got from **onCropComplete**
<Cropper onCropComplete={onCropComplete}  /> component with default crop area.

Can You help me in generating this default values without using <Cropper />.

**Comment by ValentinH** [comment]
I'm sorry but I only offer support for this library.

**Comment by buncis** [comment]
@HarishReddyCH go to stackoverflow or other react community for that kind of questions

the issue is for reporting bug about the library not a question how to use it.

**Comment by HarishReddyCH** [comment]
@buncis  Thanks.....
I have already found a solution to get it
