### ISSUE TITLE
Setting the default width and height for the crop area

### ISSUE THREAD

**Issue by JoshuaEdigbe** [ricardo-ch/react-easy-crop#247]
I need help. 

I want to set the default crop frame width and height to 350 X 350px, how do I achieve this?

**Comment by ValentinH** [comment]
Set the parent container to that dimensions and use aspect=1 on the cropper

**Comment by JoshuaEdigbe** [comment]
@ValentinH thanks for helping out. 

I try this but it didn't work. Like I always want the output image to be 350 X 350px.

**Comment by ValentinH** [comment]
What you want is basically explained in https://github.com/ricardo-ch/react-easy-crop/issues/176
