### ISSUE TITLE
Support for vertical video 

### ISSUE THREAD

**Issue by codeRuth** [ricardo-ch/react-easy-crop#251]
It would be great if there was a support for vertical video, since these kinds of videos are most in need of cropping, the lib currently has the crop area is zoomed in and it doesn't span the whole height, and it doesn't allow pan to the restricted area.

i tried changing the object fit of the .video to contain to fit the aspect ratio, bu then the `restrictPosition` dosen't work, the crop area goes beyond the video itself.

**Comment by ValentinH** [comment]
Could you share a codesandbox of what you're trying to do? It will be easier for me to understand what you tried so far. Videos should not be different than images for this library so vertical videos should not be an issue.

**Comment by codeRuth** [comment]
Thanks @ValentinH  for the quick reply, I just tested out in a codesandbox, seperate from the project, it is working fine, with no issues.

I am trying to place the react-easy-crop in modal/dialog which has height limitations. Correct me if im wrong, is it necessary to have the container height equal or greater than media height?

Is it possible to have it in a modal/dialog which has height limitations. Also I really don't have scope to make it a full page dialog.

**Comment by codeRuth** [comment]
Thanks  [@ValentinH](https://github.com/ValentinH)  for the quick reply, I just tested out in a codesandbox, seperate from the project, it is working fine, with no issues.
I am trying to place the react-easy-crop in modal/dialog which has height limitations. Correct me if im wrong, is it necessary to have the container height equal or greater than media height?
Is it possible to have it in a modal/dialog which has height limitations. Also I really don’t have scope to make it a full page dialog.

**Comment by ValentinH** [comment]
The only requirement is to have the container have `position: relative` so that the cropper can fill it. I guess you should give it an explicit width and height though.
On https://www.ricardo.ch, we also use this library in a dialog.

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉
