### ISSUE TITLE
Resize crop area using corner handles

### ISSUE THREAD

**Issue by anishjana** [ricardo-ch/react-easy-crop#254]
**Describe the bug**
Is there a way to keep image static and move the crop area alongwith with abilty to resize it?

**Expected behavior**
![resize](https://user-images.githubusercontent.com/52600343/119622491-d4030580-be24-11eb-8957-30ba02576243.PNG)

- Please create a CodeSandbox that demonstrates your issue. You can fork the Basic example: https://codesandbox.io/s/react-easy-crop-v69ly910ql.

**Comment by ValentinH** [comment]
No this is not possible and this is not the goal of the library. I actually created it because there was already libraries to crop from corners but none that was doing what this one is doing.

https://github.com/DominicTobias/react-image-crop should do what you want.
