### ISSUE TITLE
It can not crop image when user take photo in the safari.

### ISSUE THREAD

**Issue by thuonghdbhsoft** [ricardo-ch/react-easy-crop#261]
**Describe the bug**

**To Reproduce**
1. Go to 'Safari iphone'
2. Click on 'Upload image then click show result button'
3. Scroll down to '.'

**Expected behavior**
Image empty
![IMG_1650](https://user-images.githubusercontent.com/38204111/120768111-05c34d00-c546-11eb-8f6e-f3512694dc1c.PNG)

**Comment by ValentinH** [comment]
Do you have the same issue on the demo website: https://ricardo-ch.github.io/react-easy-crop/ ?

What error do you see?

**Comment by thuonghdbhsoft** [comment]
I check both site.
It can't render image.
 https://ricardo-ch.github.io/react-easy-crop/ 
https://codesandbox.io/s/y09komm059

**Comment by ValentinH** [comment]
What version of iOS ? I just tried on iOS 14.5 and the demo website works fine.
However, I do see the same issue on the sandbox.

**Comment by thuonghdbhsoft** [comment]
You try to choose to take photo in your iphone.

**Comment by ValentinH** [comment]
I suspect a security limitation on codesandbox because the blob shown in the popup is coming from another domain. Do you have the same issue outside codesandbox?

**Comment by thuonghdbhsoft** [comment]
The sandbox has no effect on that example. I looked at react-image-crop package, it works fine.
https://codesandbox.io/s/react-image-crop-demo-with-react-hooks-y831o

**Comment by thuonghdbhsoft** [comment]
I think. It is this issue.
https://stackoverflow.com/questions/35500999/cropping-with-drawimage-not-working-in-safari

**Comment by chimpaji** [comment]
@ValentinH Picture not show on picture taken by iPhone, i try on your codesandbox on all browser in iOS14.X

**Comment by ValentinH** [comment]
OMG Safari is the new IE, such a pain in the ass 🙈

**Comment by thuonghdbhsoft** [comment]
Since, canvas does not get the size of images with large pixels. So, my solution is to compress the image with this package.
https://www.npmjs.com/package/browser-image-compression

**Comment by ValentinH** [comment]
What was the original size of your image?

**Comment by thuonghdbhsoft** [comment]
Photos taken from iphone 8 plus and image size > 10MB

**Comment by ValentinH** [comment]
As the actual cropping using Canvas operations are not part of this library and just provided as examples, I'm going to close this issue. Also, OP suggested a solution: resizing the image before cropping it.

**Comment by chimpaji** [comment]
@thuonghdbhsoft any tips for detect if the file is a iphone's format? So we can run compress package on specific file.
