### ISSUE TITLE
Cropped image not exactly matching the aspect ratio

### ISSUE THREAD

**Issue by jchanoo** [ricardo-ch/react-easy-crop#268]
The cropped image does not exactly match the aspect ratio. It has slight difference.

I tried cropping image with different aspect ratio via the following link:
https://codesandbox.io/s/q8q1mnr01w

Lets get your dog image (1910x1000px), aspect ratio (4:3), and no zoom as an example.
The resulting cropped image has a size of 1333x1000px, 1.333 aspect ratio, which is slightly different from 1.33333333333.

I have a suggestion:
Lets take 4/3 as the target aspect ratio.
1910/4 = 477.5 > Get .floor > ~477
1000/3 = 333.333... > ~333
Then we take the minimum one, i.e., 333.

cropwidth: 4*333 = 1332
cropheight: 3*333 = 999
Hence, aspect ratio = 1332/999 = 4/3

Then, in this case, we will get the largest cropped image that EXACTLY matches the target aspect ratio.

**Comment by ValentinH** [comment]
The thing is that one requirement is for the default crop size to have one side that exactly matches the image size (1000px in your example). I don't think we can have this and the perfect precision at the same time.

I'm also wondering if your example works with any image size.

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉
