### ISSUE TITLE
Webpack does not support your project?

### ISSUE THREAD

**Issue by lapaz17** [ricardo-ch/react-easy-crop#269]
**Describe the bug**
After Webpack , it shows tiny image.  Adding ss:
![image](https://user-images.githubusercontent.com/39624400/122686033-ca986d80-d217-11eb-8627-2129d0d6a5e4.png)

**To Reproduce**
I added a repo below. You can clone and try it yourself.

**Expected behavior**
Full Size should be shown.

- Please create a CodeSandbox that demonstrates your issue.
https://github.com/lapaz17/React-Easy-Crop-webpack-example

Btw, I tried same code on CodeSandbox and it works perfect. So, I guess problem is related to webpack.

**Comment by ValentinH** [comment]
All the demo examples are using webpack so there is probably nothing to do with this. 

After having a quick look at your example, I think this is due to the way you used the modal. Please first try without the modal.

**Comment by lapaz17** [comment]
Yes, you are right. I will ask counterpart question on modal. Thanks for fast response.
