### ISSUE TITLE
Show the Image in full Area of class crop-container.

### ISSUE THREAD

**Issue by vparade** [ricardo-ch/react-easy-crop#271]
![image](https://user-images.githubusercontent.com/85477027/123242858-10974f00-d500-11eb-9f2c-62619ba38b7d.png)

As shown in above image I wanted to remove the grey portion of image. Currently Incase I click and more the cursor to left/right the grey portion seems at left top and bottom. 

I want the image to cover entire portion of crop-container.

for any changes please refer this link: https://codesandbox.io/s/react-easy-crop-demo-forked-u6o8z?file=/src/index.js

**Comment by ValentinH** [comment]
You should be able to use the objectFit prop for this.

**Comment by vparade** [comment]
@ValentinH I has already used objectFit.
If I add  **objectFit="conatin"** the image looks totally weird. I mean the image seems totally zoomed in this case.

Check the screenshoot bellow
![image](https://user-images.githubusercontent.com/85477027/123247346-6ec63100-d504-11eb-9311-1943e0a2d0d2.png)

**Comment by ValentinH** [comment]
conatin is not a valid value

**Comment by ValentinH** [comment]
See https://codesandbox.io/embed/react-easy-crop-forked-p9r34

**Comment by vparade** [comment]
> See https://codesandbox.io/embed/react-easy-crop-forked-p9r34

I had referred same link still I have issues.

please have a look at once to bellow link
https://codesandbox.io/s/react-easy-crop-demo-forked-u6o8z?file=/src/index.js

can **cropShape="round", aspect={1} matter**?

**Comment by ValentinH** [comment]
I think you want to use `vertical-cover`, see the result: 
![image](https://user-images.githubusercontent.com/2678610/123294299-029ff900-d515-11eb-9f45-7af9d03b6baa.png)

**Comment by vparade** [comment]
done with issue with above comment
