### ISSUE TITLE
How can I upload gif to base64?

### ISSUE THREAD

**Issue by LansPeti** [ricardo-ch/react-easy-crop#283]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

- If you have ideas how to implement your new feature, please share!

- If you know any examples online that already implement such functionality, please share a link.

**Comment by ValentinH** [comment]
I have no idea and I don't really think this is possible (or at least the string will be huge).

On a side note, the goal of an issue template is to be replaced with your actual content. 😉
