### ISSUE TITLE
Grid not showing up

### ISSUE THREAD

**Issue by Chetanr** [ricardo-ch/react-easy-crop#290]
**Describe the bug**
Grid Not showing up when creating an onClick event.

After uploading the image, I render the image using the <img/> tag. I then try to crop using the crop button by calling the cropper. But the grid is not showing up in this case. It works properly if I call the cropper when there is an onChange event for the <input> of type file.

Can you please have a look at the code and help me on where I am going wrong. I want the cropping feature to be showing using button click

https://codesandbox.io/s/react-easy-crop-demo-forked-voc08?file=/src/cropImage.js

**Comment by ValentinH** [comment]
Here's the fixed version: https://codesandbox.io/s/react-easy-crop-demo-forked-gup5k?file=/src/ChooseImage.js

The solution is to not rely on elements `display` style but to actually render them or not. In general, this is how you should do in React when you want to conditionally show a component.

**Comment by Chetanr** [comment]
Thanks, Valentin. It is working now.

*Thanks and Regards,*
*Chetan Revappa*
*Linkedin: *https://www.linkedin.com/in/chetan-r/

**Comment by ValentinH** [comment]
You are welcome

**Comment by Chetanr** [comment]
Hi,
Is it possible to make the cropping area to be specified by the user rather
than pre-fixing it?

*Thanks and Regards,*
*Chetan Revappa*
*Linkedin: *https://www.linkedin.com/in/chetan-r/

**Comment by ValentinH** [comment]
No this is not possible and this would be against the original purpose of this cropper. There are other libraries that should do what you want.
