### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation while clicking the picture in Chrome device emulation

### ISSUE THREAD

**Issue by esiale** [ricardo-ch/react-easy-crop#291]
Hello there,
I've encountered a weird bug while developing my website using react-easy-crop. While using Chrome and running device emulation, a console error appears "Unable to preventDefault inside passive event listener invocation" after touching the uploaded image. This doesn't seem to happen in Firefox. Curiously I wasn't able to reproduce the same bug while forking and running the examples. It appears it's something with my implementation which is causing the error.

I've pushed my project to CodeSandbox and stripped it down so that it only contains the cropping portion. 

This bug is not breaking but slightly annoying.

1. Go to https://codesandbox.io/s/crop-sprqk in Chrome
2. Choose a picture file, go to Google Dev Tools, run device emulation
3. Click on the picture or drag it (still in Cropping mode)

**Comment by ValentinH** [comment]
Thanks for reporting. I guess this `preventDefault()` call should be removed but I need to test it on real devices just in case.

**Comment by ValentinH** [comment]
This should be fixed with v3.5.3
