### ISSUE TITLE
Can't import Typescript types

### ISSUE THREAD

**Issue by pedrosimao** [ricardo-ch/react-easy-crop#293]
**Describe the bug**
I have followed the Codesandbox example, but I get an error saying: `Package subpath './types' is not defined by "exports"`
I also get the following eslint issue: `ESLint: Unable to resolve path to module 'react-easy-crop/types'.(import/no-unresolved`

**To Reproduce**
It is difficult to provide a perfect environment to reproduce the bug. Especially since it seems to work fine on Codesandbox. But I am using CRA...

**Expected behavior**
Be able to import TS Types without errors.

**Comment by ValentinH** [comment]
Indeed, this is an issue with the import map here: https://github.com/ricardo-ch/react-easy-crop/blob/f5ed05dd4c86be72635a0f071a8da06d9ccaa3b1/scripts/copy-build-files.js#L28

Would you like to make a PR to add the right import there?

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉

**Comment by ooyyloo** [comment]
@ValentinH "types" field in newPackageData should be moved into exports.
Refer to [enhanced-resolve issue 341](https://github.com/webpack/enhanced-resolve/issues/341)

**Comment by ValentinH** [comment]
Thanks, would you like to make a PR for it?
