### ISSUE TITLE
JSX element class does not support attributes because it does not have a 'props' property.ts(2607)

### ISSUE THREAD

**Issue by RicciardiCharles** [ricardo-ch/react-easy-crop#294]
Hello,

The Cropper works perfectly fine, however I still get this error: 

> TS2786: 'Cropper' cannot be used as a JSX component.
>  Its instance type 'Cropper' is not a valid JSX element.
>    Type 'Cropper' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, refs

I declared the cropper in a function like that: 
`<Cropper
                                    cropShape= "round"
				    disableAutomaticStylesInjection="true"
				    image={image}
			            crop={crop}
				    zoom={zoom}
				    aspect={1}
				    onCropChange={setCrop}
				    onZoomChange={setZoom}
				    onCropComplete={onCropComplete}
/>`

**Comment by ValentinH** [comment]
Are you able to reproduce this issue in a codesandbox?

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉

**Comment by VikariiCGI** [comment]
Hi @ValentinH,
I have the same issue. And this related with react import. 
![image](https://user-images.githubusercontent.com/74358381/140507787-06ba39b2-0ab4-4d46-a1fd-b3e62dc05bfd.png)
I do import 
![image](https://user-images.githubusercontent.com/74358381/140507863-67f4da27-ce2c-4c84-bc20-15c94181c010.png)

**Comment by VikariiCGI** [comment]
![image](https://user-images.githubusercontent.com/74358381/140507893-524f38e7-ae7b-4e0c-af18-708d0c46cc18.png)

**Comment by ValentinH** [comment]
Are you able to create an example showing the issue that I could have a look at?

**Comment by VikariiCGI** [comment]
I have tried in codesandbox.io, but I can`t reproduse :( 
Anyway my solution was  
1) go to `node_modules\react-easy-crop\index.d.ts`
2) change 1st row to `import * as React from "react"; `
