### ISSUE TITLE
Module resolution problems in examples

### ISSUE THREAD

**Issue by nicklasfrahm** [ricardo-ch/react-easy-crop#30]
## Are you reporting a bug?

- Please create a CodeSandbox that demonstrates your issue. You can fork the [Basic example](https://codesandbox.io/s/q80jom5ql6).

  [Basic example](https://codesandbox.io/s/q80jom5ql6)

- Provide the steps to reproduce the issue, e.g.:

  1.  Run the example in codesandbox
  2. Wait for transpilation to finish

  **Observed behaviour:** ModuleNotFoundError
Could not find module in path: '@babel/runtime/helpers/builtin/interopRequireDefault' relative to '/node_modules/@material-ui/lab/Slider/index.js'

  **Expected behaviour:** The example renders correctly.

**Comment by ValentinH** [comment]
Thanks for reporting! 

Upgrading to latest `@material-ui/*` fix the issue. I'll   save the fixed sandbox once I'm on the computer 🙂

**Comment by ValentinH** [comment]
All demos from the readme are fixed 😉
