### ISSUE TITLE
How can I change the background color of the cropped image to transparent?

### ISSUE THREAD

**Issue by chuongvuoop2021** [ricardo-ch/react-easy-crop#308]
**Describe the issue:**
Right now when I try to crop an image with transparent background, it would automatically change that background color to black, is there anyway I can change this?
**To Reproduce**
download an image with transparent background then use crop tool to crop it, the background will turn black.
![pngwing com](https://user-images.githubusercontent.com/59803622/139427831-e06b8b4e-263a-4398-9766-01dbd14d7b28.png)

![image](https://user-images.githubusercontent.com/59803622/139427812-14dfb672-ab7d-441f-b3c3-ce2584bda6cd.png)
Expected behavior
the cropped image's background should have the same color with the original one

**Comment by ValentinH** [comment]
You should set the exported image to be a png in the crop image.js file. See https://github.com/ValentinH/react-easy-crop/issues/165#issuecomment-711417984

**Comment by chuongvuoop2021** [comment]
> You should set the exported image to be a png in the crop image.js file. See [#165 (comment)](https://github.com/ricardo-ch/react-easy-crop/issues/165#issuecomment-711417984)

that worked, thank you very much!

**Comment by ianWins2n** [comment]
> You should set the exported image to be a png in the crop image.js file. See https://github.com/ricardo-ch/react-easy-crop/issues/165#issuecomment-711417984

im having the same issue, this link is not working anymore

**Comment by ValentinH** [comment]
Here it is: https://github.com/ValentinH/react-easy-crop/issues/165#issuecomment-711417984

@ianWins2n

**Comment by ianWins2n** [comment]
> Here it is: [#165 (comment)](https://github.com/ValentinH/react-easy-crop/issues/165#issuecomment-711417984)
> 
> @ianWins2n

thanks
