### ISSUE TITLE
Moving images with zoom smaller than 1 not possible

### ISSUE THREAD

**Issue by nicklasfrahm** [ricardo-ch/react-easy-crop#31]
## Are you reporting a bug?

- Please create a CodeSandbox that demonstrates your issue. You can fork the [Basic example](https://codesandbox.io/s/q80jom5ql6).

  https://codesandbox.io/s/92r5r56zqr?fontsize=14

- Provide the steps to reproduce the issue, e.g.:

  1.  Try to move the image

  **Observed behaviour:** It is not possible to move the image within the cropping boundaries if the zoom is smaller than `1`.

  **Expected behaviour:** Zooms smaller than `1` should be supported in order to not only crop, but also change the aspect ratio of an image. In my application I'd like to get images with a constant aspect ratio. For the best UX I'd like the user to be able to also just use any image with a white background. Vertical images are especially a problem. A possible implementation could be to modify the `restrictPosition` function. I do a lot of JS myself, but if you have a quick fix for this it would be great to see this improvement to this overall very nice project!

**Comment by ValentinH** [comment]
Hey, thanks for the really detailed issue.

I'm not sure what would be the expected behavior here, how moving the image would change the aspect ratio...
I think that if the image is smaller than the container, it might be the role of the client app to set the container size to match the image.

**Comment by nicklasfrahm** [comment]
Sorry, if I was unclear about explaining this. The idea is to give the user the possibility to move the image within the boundaries, even if it is smaller than the boundaries. This gives to possibility to include all necessary content, while still forcing a specific aspect ratio for later use in your app. 

I have replaced the image. This is less applicable for my use-case but might explain it a bit better.

I'd like to be able to move the image such that I can align the bottom right corner of the image with the bottom right corner of the container even if the image remains at the same zoom. I think we could potentially remove the `restrictPosition` functionality if the image is smaller than the boundary box.

Please let me know if I am not making any sense.

**Comment by ValentinH** [comment]
Thanks for clarifying I get it now :)
Would you like to submit a PR for this?

**Comment by nicklasfrahm** [comment]
Would love to, but how should we do this? The easiest way would be to add a prop that allows the user to disable the `restrictPosition` functionality. Something like `<Cropper restrictPosition={false} />`? The use has then the full power to do fancy stuff like this as well `<Cropper zoom={zoom} restrictPosition={zoom >= 1} />`.

**Comment by ValentinH** [comment]
Yes I like this pretty much! Just need to set the default to true so we keep the same default behavior :)

**Comment by nicklasfrahm** [comment]
@ValentinH PR is ready.
