### ISSUE TITLE
Bug in Safari

### ISSUE THREAD

**Issue by alenssy** [ricardo-ch/react-easy-crop#311]
Bug only in Safari 15:
- Initially, when uploading video to cropper, it is not displayed
- When there is a picture in the cropper and you change it to the video - it is not displayed, if you change the video to video, then everything works fine.

**Comment by ValentinH** [comment]
Could you please create a codesandbox showing the issue please?

**Comment by alenssy** [comment]
https://codesandbox.io/s/young-microservice-gidiu

**Comment by ValentinH** [comment]
I just opened your sandbox in Safari and I don't notice any issue. Could you please describe a bit more how to see the issue or provide a sandbox directly showing what is wrong?

**Comment by alenssy** [comment]
I apologize for your wasted time. This bug occurred in our application, not in your library. I close this issue

**Comment by alexsprings** [comment]
Hey @ValentinH 

I have Safari 15.0 running on MacOS 11.6
When I open sandbox in Safari I can't see the video preview in Cropper but I can see it as a plain video HTML element.
![image](https://user-images.githubusercontent.com/5611460/143132229-9a5bb1e4-c567-4f32-9559-01704db4ae24.png)

But when I open the same link in Chrome I can see both videos:
![image](https://user-images.githubusercontent.com/5611460/143132418-38949b44-e67a-4325-bedf-be5a742438c4.png)

**Comment by alenssy** [comment]
updated sandbox https://codesandbox.io/s/young-microservice-gidiu?file=/src/App.js

**Comment by ValentinH** [comment]
Unfortunately I'm still on Big Sur so I have Safari 14.1. Indeed, there is no issue there.

On Safari 15, do you see any issues in the console?

**Comment by alexsprings** [comment]
No, nothing related in the console. And yes for me it works well on Safari 14 as well. The issue is only for 15.

**Comment by trurl-master** [comment]
Just tried it in Safari 15.1 - seems to work fine

**Comment by ValentinH** [comment]
@alexsprings could you confirm that the issue is fixed on Safari 15.1? It might also be the latest 4.0.0 version released yesterday that fixed it.

**Comment by alexsprings** [comment]
@ValentinH We just upgraded to 4.0.0 and I don't see a bug anymore! Thank you for your help!
