### ISSUE TITLE
Bug on desktop and ios Safari with big image

### ISSUE THREAD

**Issue by xenogearsX** [ricardo-ch/react-easy-crop#318]
When you have a big image to crop and want to get the image back before saving there is an error
https://codesandbox.io/s/react-easy-crop-demo-with-cropped-output-forked-2urjl
When you hit show image on safari, it's not working and we get an error in console :
     for desktop safari codesandbox:
          getImageData@[native code]
          @
          asyncFunctionResume@[native code]
          @[native code]
          promiseReactionJobWithoutPromise@[native code]
          promiseReactionJob@[native code]

    for my wip website :
         Unable to get image data from canvas. Requested size was 7240 x 7240
         Unhandled Promise Rejection: InvalidStateError: The object is in an invalid state.

No issue on android and desktop chrome/firefox

**Comment by ValentinH** [comment]
We just released v4.0.0 that should improve this issue. Please have a look to the latest sandbox 🙂

**Comment by xenogearsX** [comment]
Thanks a lot I was indeed on an old version.
Safari is working on 4.0.0.

**Comment by ValentinH** [comment]
One more issue fixed @trurl-master 👏

**Comment by tvankith** [comment]
https://github.com/ValentinH/react-easy-crop/issues/91#issuecomment-766167263 solved my issue
