### ISSUE TITLE
Output of cropArea does not make sense for zooms smaller than 1 if restrictPosition is false

### ISSUE THREAD

**Issue by nicklasfrahm** [ricardo-ch/react-easy-crop#33]
## Are you reporting a bug?

- Please create a CodeSandbox that demonstrates your issue. You can fork the [Basic example](https://codesandbox.io/s/q80jom5ql6).

  [Fork of **Example with output of the cropped image**](https://codesandbox.io/s/v3y521y7l)

  **Note: I have also modified the `getCroppedImg` function.**

- Provide the steps to reproduce the issue, e.g.:

  1.  Click on **Show image**

  **Observed behaviour:** The image is zoomed in. The zoom is clearly `>=1` and the cropped image does not have a white border as expected.

  **Expected behaviour:** If the position is not restricted and the zoom is smaller than `1`, the `cropArea` and `cropAreaPixels` is calculated correctly and allows cropArea sizes bigger than the maximum image dimensions.

I have looked at the source code and it seems like the `limitArea` function is doing the trick here. If I understand the function correctly, we should not use it if the zoom is smaller than `1` and if `restrictPosition={false}`, because it will not allow the cropArea to be bigger than the image. However, I am not sure if I understand the function correctly in the context of `setCalculatedCrop`.

**Comment by ValentinH** [comment]
Hey thanks for continuing on this topic.

Could you please review #35 and tell me if it matches what you expect?

**Comment by ValentinH** [comment]
Closed by #35 and released at 1.11.1

**Comment by nicklasfrahm** [comment]
@ValentinH In the new codesandbox you added, we have another one of these: _Warning: Failed prop type: Material-UI: the `raised` variant will be removed in the next major release. `contained` is equivalent and should be used instead._

**Comment by ValentinH** [comment]
Well-caught, fixed 🙂

**Comment by nicklasfrahm** [comment]
Kudos! You do great work. 🚀
