### ISSUE TITLE
Crop image using CSS

### ISSUE THREAD

**Issue by abstractedillusion** [ricardo-ch/react-easy-crop#331]
Hi, first off amazing library, saved a ton of work for me.

So, based on he demos on the project page, the examples uses a canvas based approach to crop and zoom the image. I wanted the same with just CSS(dont know if this has been pointed out in any of the closed issues, if yes please direct me to the issue page), I tried using the methods listed in the following link, but it does not seem to reflect the the original cropped positions in the cropper. 

[https://auralinna.blog/post/2018/crop-and-resize-images-with-css](https://auralinna.blog/post/2018/crop-and-resize-images-with-css)

Could you help me out, or direct me in a proper direction, I seem to have tried every method(even clip: rect and clip-path: inset, but no avail)

Thanks in Advance.

**Comment by ValentinH** [comment]
I think that this example by @trurl-master  should help you: https://codesandbox.io/s/usecroppedimage-mhe57?file=/src/useCroppedImage.ts

**Comment by trurl-master** [comment]
@ValentinH do you think putting it into the lib is a good idea? As a utility hook. I mean it's not a trivial thing to solve, maybe it will help people.

This example is a bit too difficult though, it's doesn't rely on width/height of the container, only on the fact that the image inside the container is proportional to the width of the container. If you know the width and height, it should be much easier

**Comment by ValentinH** [comment]
I'm not sure because it's an advanced usage that brings even more complex logic to maintain. If people need this, I would first add it to the list of examples on the Readme.

**Comment by abstractedillusion** [comment]
> I'm not sure because it's an advanced usage that brings even more complex logic to maintain. If people need this, I would first add it to the list of examples on the Readme.

Please Do

**Comment by ValentinH** [comment]
Do you mean that the example I linked above matches what you needed?

**Comment by abstractedillusion** [comment]
yes it does, but it seems to be a bit complicated, maybe it could be dumbed down for newbies.

**Comment by trurl-master** [comment]
I'm not sure I can. I kinda brute forced the solution, solving the math for 4 different cases: `<90˚`, `90˚-180˚`, `180˚-270˚` and `>270˚`, but I'm not at all sure that it's the cleanest one.

But if you don't care about rotation, you can substitute `0` for `rotation` and simplify it to basically:

```js
const scale =  croppedArea.width / 100

{
  x: `${-croppedArea.x * scale}%`,
  y: `${-croppedArea.y * scale}%`,
  scale,
  width: "calc(100% + 0.5px)",
  height: "auto",
}
```

That one is much easier to understand. The general case just adjusts all these values taking rotation into account.

**Comment by ValentinH** [comment]
Here's the version I came up while trying to simplify @trurl-master original version to the maximum (by dropping the rotation support): https://codesandbox.io/s/usecroppedimage-forked-kkqj0?file=/src/App.jsx

Do you think it's good enough to be listed on the README?

**Comment by abstractedillusion** [comment]
> Here's the version I came up with while trying to simplify @trurl-master original version to the maximum (by dropping the rotation support): https://codesandbox.io/s/usecroppedimage-forked-kkqj0?file=/src/App.jsx
> 
> Do you think it's good enough to be listed on the README?

Yes, it is simple and easy to understand.

**Comment by ValentinH** [comment]
I just added this to the reame.

**Comment by lashakaraulashvili** [comment]
Hello, his doesn't work on rotation? @ValentinH

**Comment by ValentinH** [comment]
No but you can support rotation by using the more advanced examples shared above.
