### ISSUE TITLE
For IOS take photo or chosse lib not worked I see black screen

### ISSUE THREAD

**Issue by mxomxo77mxo** [ricardo-ch/react-easy-crop#335]
For IOS 
1 click upload image
2 choose take photo
3 crope or continue
I see black screen

**Comment by ValentinH** [comment]
Please use the search to find related issues: https://github.com/ricardo-ch/react-easy-crop/issues?q=is%3Aissue+sort%3Aupdated-desc+black+is%3Aclosed

This one has been discussed many times.
