### ISSUE TITLE
Material UI Button variant type warning in example

### ISSUE THREAD

**Issue by nicklasfrahm** [ricardo-ch/react-easy-crop#34]
## Are you reporting a bug?

- Please create a CodeSandbox that demonstrates your issue. You can fork the [Basic example](https://codesandbox.io/s/q80jom5ql6).

  I have checked all examples and it seems like only the following is affected:
  [Example with output of the cropped image](https://codesandbox.io/s/q8q1mnr01w)

- Provide the steps to reproduce the issue, e.g.:

  1.  Open the console in codesandbox (in webapp, not `F12`)

  **Observed behaviour:** Warning: Failed prop type: Material-UI: the `raised` variant will be removed in the next major release. `contained` is equivalent and should be used instead.

  **Expected behaviour:** No warning in console.

Should be a quick fix by just replacing `variant="raised"` with `variant="contained"` for the `<Button />` component.

**Comment by ValentinH** [comment]
Done 👍
