### ISSUE TITLE
Cropper encapsulation

### ISSUE THREAD

**Issue by FloFlex** [ricardo-ch/react-easy-crop#341]
I'm trying to embed the react-easy-crop editor in web page but when I insert the module, it takes the whole page. 

What is the best way to change the dimensions of the module to fit the destination area of my page ?

**Comment by ValentinH** [comment]
This is explained in the readme: 
![Screenshot_20220120-095318](https://user-images.githubusercontent.com/2678610/150305465-c004eda9-3767-4af1-ab0f-546dc6642b89.jpg)

**Comment by FloFlex** [comment]
Dear Valentin,

I missed it. Thanks a lot. I'll try right now.

Best Regards,
Florian Pernisek

----- Mail d'origine -----
De: Valentin Hervieu ***@***.***>
À: ricardo-ch/react-easy-crop ***@***.***>
Cc: FloFlex ***@***.***>, Author ***@***.***>
Envoyé: Thu, 20 Jan 2022 09:54:02 +0100 (CET)
Objet: Re: [ricardo-ch/react-easy-crop] Cropper encapsulation (Issue #341)

This is explained in the readme:
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by oleksi-l** [comment]
@ValentinH Seems problem solved

**Comment by FloFlex** [comment]
Hi Olesksii,

 Sorry for my late answer. In fact, the "relative" attribut only allows to change the width, but not the height using the CodeSandBox examples. 

In reality, I'm trying to embed the cropper module into a react form class. I suspect that I have to use a CSS style within this class to play around with the module position and dimension within this form.

Would you have an online example (such as CodeSandbox)  to share that shows a more complex integration so that I can grab some inspiration ?

Thanks in advance,
Florian

----- Mail d'origine -----
De: Oleksii ***@***.***>
À: ricardo-ch/react-easy-crop ***@***.***>
Cc: FloFlex ***@***.***>, Author ***@***.***>
Envoyé: Tue, 25 Jan 2022 05:11:53 +0100 (CET)
Objet: Re: [ricardo-ch/react-easy-crop] Cropper encapsulation (Issue #341)

@ValentinH Seems problem solved—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by oleksi-l** [comment]
Florian, please codesandbox example, I ll try to help you
