### ISSUE TITLE
White border show on top of the image

### ISSUE THREAD

**Issue by faisalch10** [ricardo-ch/react-easy-crop#343]
I used react easy crop to crop images on client side and then uploaded on backend. But i face issue related to to white border that shows at top of the images with dark color. Before i was facing issue regarding to left border in BLACK COLOR show on left side of the image but that issue fixed by adding below 2 lines of code

  ctx.fillStyle = 'white';
  ctx.fillRect(0, 0, canvas.width, canvas.height);
  
  But now white border show on top of the image. Please help
![Capture](https://user-images.githubusercontent.com/57663488/152350132-52ae7d92-b346-44c6-a5eb-835135b9fe06.PNG)

**Comment by ValentinH** [comment]
This is probably due to rounding issues in the canvas cropping logic. 

Could you share a sandbox with the code you are using along with the image causing the issue please?

**Comment by faisalch10** [comment]
> This is probably due to rounding issues in the canvas cropping logic.
> 
> Could you share a sandbox with the code you are using along with the image causing the issue please?

I can share you the cropImage file not the sandbox because there is A LOT of code here and there

**Comment by ValentinH** [comment]
Sure, anything that can help pinpoint the issue will allow me to help you.

**Comment by faisalch10** [comment]
Here the code of cropImage.js file.

I added below two lines in order to remove black border on left side. But as i mentioned in the issue that now i am facing white border on top of the black images.

  // * I ADDED BELOW TWO LINES
  ctx.fillStyle = 'white';
  ctx.fillRect(0, 0, canvas.width, canvas.height);

/**
 * This function was adapted from the one in the ReadMe of https://github.com/DominicTobias/react-image-crop
 * @param {File} imageSrc - Image File url
 * @param {Object} pixelCrop - pixelCrop Object provided by react-easy-crop
 * @param {number} rotation - optional rotation parameter
 */

const createImage = (url) =>
  new Promise((resolve, reject) => {
    const image = new Image();
    image.addEventListener('load', () => resolve(image));
    image.addEventListener('error', (error) => reject(error));
    image.setAttribute('crossOrigin', 'anonymous'); // needed to avoid cross-origin issues on CodeSandbox
    image.src = url;
  });

function getRadianAngle(degreeValue) {
  return (degreeValue * Math.PI) / 180;
}

export default async function getCroppedImg(imageSrc, pixelCrop, rotation = 0) {
  const image = await createImage(imageSrc);
  const canvas = document.createElement('canvas');
  const ctx = canvas.getContext('2d');

  const maxSize = Math.max(image.width, image.height);
  const safeArea = 2 * ((maxSize / 2) * Math.sqrt(2));

  // set each dimensions to double largest dimension to allow for a safe area for the
  // image to rotate in without being clipped by canvas context
  canvas.width = safeArea;
  canvas.height = safeArea;

  // translate canvas context to a central location on image to allow rotating around the center.
  ctx.translate(safeArea / 2, safeArea / 2);
  ctx.rotate(getRadianAngle(rotation));
  ctx.translate(-safeArea / 2, -safeArea / 2);

  // * I ADDED BELOW TWO LINES
  ctx.fillStyle = 'white';
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  // draw rotated image and store data.
  ctx.drawImage(
    image,
    safeArea / 2 - image.width * 0.5,
    safeArea / 2 - image.height * 0.5
  );

  const data = ctx.getImageData(0, 0, safeArea, safeArea);

  // set canvas width to final desired crop size - this will clear existing context
  canvas.width = pixelCrop.width;
  canvas.height = pixelCrop.height;

  // paste generated rotate image with correct offsets for x,y crop values.
  ctx.putImageData(
    data,
    0 - safeArea / 2 + image.width * 0.5 - pixelCrop.x,
    0 - safeArea / 2 + image.height * 0.5 - pixelCrop.y
  );

  // As Base64 string
  // return canvas.toDataURL("image/jpeg");
  return canvas;
}

export const generateDownload = async (imageSrc, crop) => {
  if (!crop || !imageSrc) {
    return;
  }

  const canvas = await getCroppedImg(imageSrc, crop);

  canvas.toBlob(
    (blob) => {
      const previewUrl = window.URL.createObjectURL(blob);

      const anchor = document.createElement('a');
      anchor.download = 'image.jpeg';
      anchor.href = URL.createObjectURL(blob);
      anchor.click();

      window.URL.revokeObjectURL(previewUrl);
    },
    'image/jpeg',
    0.66
  );
};

**Comment by ValentinH** [comment]
This logic looks quite old, where did you get it from?

You should use the one in this example: https://codesandbox.io/embed/q8q1mnr01w

**Comment by faisalch10** [comment]
Basically i watched the tutorial on youtube how to crop and then upload in that video creator provides us the starter files  in those starter files i got that code. i will try to use the code that you pointed out in example.

Link of repo
https://github.com/manishboro/image-crop-and-zoom/blob/master/src/utils/cropImage.js

**Comment by faisalch10** [comment]
**Issue Fixed after using code that exist in codepen.** Thanks ValentinH for help. God bless you

**Comment by ValentinH** [comment]
You can close it indeed . If you want to be nice with the video author, you could suggest this fix to their repo. 🙂

**Comment by faisalch10** [comment]
Ok sure i will do that 👍
