### ISSUE TITLE
CropShape set to 'round' that does not cropped the image in right way

### ISSUE THREAD

**Issue by faisalch10** [ricardo-ch/react-easy-crop#346]
**Good Evening valentinH,**
I am facing problem when i set to cropShape='round' then the image not cropped in right way. I check your codepen here
https://codesandbox.io/s/y09komm059?file=/src/index.js

In this codepen same issue exist if we set the cropShape to 'round'.

Below the image i am cropping
![Capture](https://user-images.githubusercontent.com/57663488/153208105-690fdd12-e6b6-49df-99a9-ecf772674c81.PNG)

After image cropping successfully
![Capture](https://user-images.githubusercontent.com/57663488/153208345-dea8af5d-74a6-49ca-92a2-1ed2e47f35f3.PNG)

**Comment by ValentinH** [comment]
Indeed, you need to change the logic in the ` cropImage.js` file to support rounded images. I have no clue how to do it to be honest 🙈  This is one of the reason why this file isn't actually part of the library and only provided as an example 🙂 

However, I used the `round` layout in the past for an avatar feature and what we did was to still upload the image as a square (like in your screenshot) and made it round using CSS when displaying on the page 😉
