### ISSUE TITLE
Feature Request: onCropChange Event(Live Interaction with preview instead  of onCropComplete)

### ISSUE THREAD

**Issue by sudhakarselva** [ricardo-ch/react-easy-crop#38]
## Are you reporting a bug?

- Please create a CodeSandbox that demonstrates your issue. You can fork the [Basic example](https://codesandbox.io/s/q80jom5ql6).

- Provide the steps to reproduce the issue, e.g.:

  1.  Move the image
  2.  Resize the window

  **Observed behaviour:** The cropper is outside the image

  **Expected behaviour:** The cropper stays within the image

## Are you making a feature request?

- Please describe your use case from user journey point of view, e.g.:

  > In my application, when user use the cropper on mobile, I'd like her to be able to zoom without the slider.

- If you have ideas how to implement your new feature, please share!

- If you know any examples online that already implement such functionality, please share a link.

**Comment by sudhakarselva** [comment]
As I came across below requirement in my recent project.
*)When user crops an image,we have live preview container with image background .it has to update as user interacts with onCropChange(It gives only x and y position ,using that i was not able to achieve desired  output) instead of waiting to user to complete interaction and after updating(onCropComplete) the preview.

**Comment by sudhakarselva** [comment]
I have container of 960*510,preview image has to cover the container.Thanks

**Comment by ValentinH** [comment]
Hey, please edit the original issue to remove the example content and detail more clearly your issue.

Today we don't emit the output on each change because the function to compute it is quite costly. We could add an option to emit them onChange though. Also, I should try to always emit the data and see if it really slow the things down.

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉
