### ISSUE TITLE
Photo rotation issue on iOS device

### ISSUE THREAD

**Issue by ilyakokin** [ricardo-ch/react-easy-crop#50]
Hi, thanks for awesome library! I met the next bug, when you crop a photo in Safari on iOS the output image gets rotated.

https://codesandbox.io/s/react-easy-crop-demo-with-cropped-output-gj6kk
  
  1. Open this sandbox example in Safari on iPhone
  2. Select a photo
  3. Tap "show img"

  **Observed behaviour:** The output image gets rotated 90 degrees counter-clockwise

  **Expected behaviour:** The output image preserves same orientation as the source image

UPD:

I have found the same [issue](https://github.com/mosch/react-avatar-editor/issues/123) in another library. And we could use the same [solution](https://github.com/mosch/react-avatar-editor/issues/123#issuecomment-280934432) here (ie parse the EXIF data to get image's orientation (the values 1-8), transform the image with canvas then use it to initialise the Cropper).

**Comment by ValentinH** [comment]
Thanks for taking the time to provide a solution!
