### ISSUE TITLE
Ability to fit max cropSize width

### ISSUE THREAD

**Issue by Betree** [ricardo-ch/react-easy-crop#55]
I am working on an image cropper component for a banner and `react-easy-crop` so far keeps its promise, it's working great and is damn easy to implement -- thanks for making it happen!

I am currently facing a small issue: when the zoom is not defined yet, I would need the image to fit the full width instead of the full height.

Here's a screencast to help visualize the issue

![Peek 26-08-2019 14-47](https://user-images.githubusercontent.com/1556356/63691820-83eead80-c810-11e9-9423-f274199e4405.gif)

# Proposed solution

From my understanding, the line responsible for this is https://github.com/ricardo-ch/react-easy-crop/blob/ff9300a82dc28718921c7a825e137b8f58c35b31/src/helpers.js#L138

I'd like to introduce a new prop:
- Name: `initialFit`
- Type: Can be `"width"` or `"height"` (defaults to `height` to preserve the current behaviour).
- Description: If set to "width", the initial zoom will be set to match the full width of the container. If set to "height", the image will fit the height of the container. Default to "height".

If maintainers are ok with this, I'd be happy to make a PR to make it happen.

**Comment by ValentinH** [comment]
Hey, thanks for the kind words and the clear issue 🙂

Could you provide a codesandbox showing an example where we don't have the right fit today?

I'm always open to PR but I'd like to be sure that what you need cannot already be achieved to avoid you losing your time 😉.

**Comment by Betree** [comment]
Sure! Let's use https://codesandbox.io/s/react-easy-crop-full-width-per-default-3zgr1

Currently the initial state is this one:

![image](https://user-images.githubusercontent.com/1556356/63695319-b00e2c80-c818-11e9-9ffd-f1ddedd7a9f4.png)

What I'd need is to have the image (that is smaller than the `cropSize`) to take the full width of the view, something like this:

![image](https://user-images.githubusercontent.com/1556356/63695374-dcc24400-c818-11e9-8204-6de7f03b61a5.png)

I can't easily know the size of the image before it's added to the cropper, so it would be very tricky for me to compute the initial zoom. An alternative could be to accept the `getInitialCropFromCroppedAreaPixels` function as a prop.

**Comment by Betree** [comment]
Actually from the example above, I would (ideally) also need to be able to configure `minZoom` dynamically based on the image size to ensure that the image width never goes under `100%`.

**Comment by ValentinH** [comment]
Regarding your first issue, it seems to be automatically solved by using the `aspect` property and set it to a wide value: https://codesandbox.io/s/react-easy-crop-full-width-per-default-dpp26

Today, you can already set the `minZoom` property at any time.

**Comment by ioana-marcu** [comment]
@ValentinH I have a similar issue and not able to resolve it.
I have defined a cropSize of {width: 144, height: 144}, and I want to be able to zoom out the image so the shortest side of the image would fit inside the crop area.

Here is a screenshot of my issue. You can see that I was able to zoom out more than the crop area, and I would like to prevent that.

![Screenshot from 2019-08-28 02-07-55](https://user-images.githubusercontent.com/46750915/63814332-2d30c300-c939-11e9-870e-0a199a04e0a7.png)

If I set the aspect, the issue that I have is that the crop area gets bigger than 144px.
Is there a way to achieve this?

**Comment by ValentinH** [comment]
I think I understand now where the issue come from when developers are using `cropSize`. Originally, this property did not exist, the whole logic was based on `aspect`. `cropSize` was added by a contributor who wanted to have full control on how to show and position the cropper (by manually computing the original `crop`, `zoom` and `cropSize` props.

When this component mount, it fits the image to its parent container. Then, when `aspect` is used, we compute the `cropSize` from the image width and height on screen so that the smaller side of the image fits one of the sides of the cropper.

Just to understand your use case, why do you need to set the exact size of the cropper? As the image is scaled on screen, if we make the image fit the cropper in this case, the resulting cropped image won't be 144px wide.

Actually, if I understand correctly, you might be able to achieve what you want by:
- set the aspect to 1
- set your parent container height to 144px
would this work?

**Comment by ioana-marcu** [comment]
@ValentinH, I also understand how this `aspect` prop works versus `cropSize`, but my client and designer want to have a controlled size crop area, which is achievable through `cropSize`.
We don't want to crop `144px` from the image, we only want the crop area to be that size.
And the issue we have is that when we have a defined `cropSize`, we don't have a way to tell the component that we want to zoom out the image until the smallest side of the image is equal to the crop area.

I thought we could calculate the `zoom` manually by taking the `width` and `height` of the image and doing some simple math around it, but I couldn't find a way to get the `img` reference so I can get its dimensions.
Do you know if that is doable?

We may want to create PR to implement the use case described above. Is that ok to you?

**Comment by ValentinH** [comment]
If both use cases are addressable by the same PR, it would be great! Therefore, PRs are welcome 🙂

**Comment by Betree** [comment]
Sorry for the late reply on this one!

My use case could also be solved by this, as well as another issue with default zoom that requires me to know the image dimensions.

@ValentinH Tell me if the following behavior work for you:

**Specs**
Prop: `onImageLoaded`
Type: `function`
Required: false
Description: 
> Called when image gets loaded. Gets passed an `imageSize` object with the following properties:
> - `width`
> - `height`
> - `naturalWidth`
> - `naturalHeight`

**Example**
```jsx
const CONTAINER_HEIGHT = 300;

const CroppedImage = ({ image }) => {
    const [crop, onCropChange] = React.useState({ x: 0, y: 0 });
    const [zoom, onZoomChange] = React.useState(1);
    return (
      <Cropper
        image={image}
        crop={crop}
        zoom={zoom}
        onCropChange={onCropChange}
        onZoomChange={onZoomChange}
        onImageLoaded={(imageSize) => {
            // Adapt zoom based on image size to fit max height
           setZoom(CONTAINER_HEIGHT / imageSize.naturalHeight);
        }}
      />
    )
}
```

**Comment by ValentinH** [comment]
If this addresses your both issues then it's great!

**Comment by ValentinH** [comment]
Published under 1.16.0 🎉 https://github.com/ricardo-ch/react-easy-crop/releases/tag/v1.16.0

**Comment by Betree** [comment]
Awesome @ValentinH, thanks for the super-quick support on this one, you rock!

**Comment by ValentinH** [comment]
Did this PR provide everything needed to close this issue?

**Comment by Betree** [comment]
To me yes, as @ioana-marcu's use case seems slightly different from the one initially reported I'd suggest to open a new issue if this needs some additional work.

**Comment by ValentinH** [comment]
I'll closing then, feel free to comment to reopen or open a new issue.

**Comment by mzvast** [comment]
this callback now renamed to `onMediaLoaded`
