### ISSUE TITLE
Circular crop

### ISSUE THREAD

**Issue by perbergland** [ricardo-ch/react-easy-crop#59]
## Are you making a feature request?

- Please describe your use case from user journey point of view, e.g.:

Our app (like many others) "fake crop" people profile images to be circular using the css [border-radius properties](https://redstapler.co/css-circle-image-tutorial). This works fine on the web but not so much in desktop email clients - [here’s a listing I found](https://www.campaignmonitor.com/css/box-model/border-bottom-right-radius/).

Because of that I'm searching for a cropper that allows me to crop by a circle rather than a square or rectangle. I found a JQuery component - [Croppie](http://foliotek.github.io/Croppie/) but wrapping it in React or rewriting it seemed like too much work.

This component seems well written and maintained so I was curious how hard it would be to add a feature that crops the image by a circle instead of a square?

I understand that rules out JPEG as an output format since there’s no accepted standard for including an alpha mask.

If you could provide some pointers I’d be happy to try modifying the code myself.

**Comment by ValentinH** [comment]
I have a very good news for you: this is already available with the `cropShape="round"` property. 

Demo: https://codesandbox.io/s/53w20p2o3n

**Comment by perbergland** [comment]
That’s great news - thank you!!!
