### ISSUE TITLE
Can't get Image to resize

### ISSUE THREAD

**Issue by offentim** [ricardo-ch/react-easy-crop#61]
Can't scale the image inside a div, it always has to take up the full screen?? Any ways around this

**Comment by ValentinH** [comment]
Did you try what's in the documentation?

> The Cropper is styled with position: absolute to take the full space of its parent. Thus, you need to wrap it with an element that uses position: relative or the Cropper will fill the whole page.

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉
