### ISSUE TITLE
zoom out until image very small

### ISSUE THREAD

**Issue by darmawan01** [ricardo-ch/react-easy-crop#65]
is it possible to zoom out to a very small image, so that it can cut all the parts needed ?

Maybe something like this:
![image](https://user-images.githubusercontent.com/23370707/66117506-4ea35f80-e607-11e9-84f9-f529c535ade0.png)

thanks before, and i really like it. easy to use

**Comment by ValentinH** [comment]
Hi @darmawan01, you can try playing with the `minZoom` and `restrictPosition` props. See this demo: https://codesandbox.io/s/react-easy-crop-with-hooks-wc76i

If this is not enough, please provide a demo of what you are trying to do 🙂

**Comment by darmawan01** [comment]
great, thanks @ValentinH . this what i looking for
