### ISSUE TITLE
How to avoid breaking out of boundaries by zooming out?

### ISSUE THREAD

**Issue by marcelotten** [ricardo-ch/react-easy-crop#66]
I have a square crop size of 256 px and need to make sure that the image covers the whole square. Therefore I want to achieve two things: 
1. Start with a zoom level high enough to cover the crop area
2. Set the minZoom dynamically so that the user can't zoom out so far that the square isn't covered anymore

Is there an easy way to do it? Maybe a working example?

I've attached a screenshot of the behaviour I want to _avoid_.
![Screenshot 2019-10-06 at 17 50 58](https://user-images.githubusercontent.com/169056/66271726-ec926680-e861-11e9-9696-d1bc6de77120.png)

**Comment by ValentinH** [comment]
Hi.

I'm not sure how to achieve this behavior with the current state of the library. Could you please provide a CodeSandbox showing the result visible in your screenshot? I might get more ideas with a running example... 🙂

**Comment by marcelotten** [comment]
Sure! https://codesandbox.io/s/react-easy-crop-with-hooks-umdkb

**Comment by ValentinH** [comment]
I'm on the phone right now, so I can't fork your example. However is a solution:
 
- Don't user cropSize instead set aspect to 1
- set your div wrapper size to 256px instead of 400px

**Comment by marcelotten** [comment]
Thanks for the fork! Unfortunately, the size of the selection frame is now depending on the picture's measurements.

For comparison:
- https://codesandbox.io/s/react-easy-crop-zoom-boundaries-2xn45
- https://codesandbox.io/s/react-easy-crop-zoom-boundaries-8pdoc

Sorry, just can't get to an working example with a 300x300 px container and a steady 256x256 px selection frame :/

**Comment by ValentinH** [comment]
I see.

This is not really possible directly with the library at the moment. However, you could still achieve what you want by computing the initial zoom value yourself.

**Comment by watch-janick** [comment]
> I see.
> 
> This is not really possible directly with the library at the moment. However, you could still achieve what you want by computing the initial zoom value yourself.

Do you have any ideas how you would do that?

**Comment by ValentinH** [comment]
You might be able to compute the zoom based on the image size and the container size.

**Comment by watch-janick** [comment]
For those interested in how I handled it:

```js
const createImage = url => new Promise((resolve, reject) => {
  const image = new Image()
  image.addEventListener('load', () => resolve(image))
  image.addEventListener('error', error => reject(error))
  image.setAttribute('crossOrigin', 'anonymous')
  image.src = url
})

const getImageDimensions = async url => {
  const image = await createImage(url)

  return {
    width: image.naturalWidth,
    height: image.naturalHeight,
  }
}

useEffect(() => {
  async function computeScaledZoom() {
    const { width, height } = await getImageDimensions(url)

    const scaledZoom = width > height
      ? width / height
      : height / width

    setInitialZoom(scaledZoom)
    setZoom(scaledZoom)
  }
  computeScaledZoom()
}, [])
```

**Comment by ValentinH** [comment]
As @watch-janick has provided an example of solution, I'm going to close this.
