### ISSUE TITLE
changing aspect state has no effect

### ISSUE THREAD

**Issue by mbretter** [ricardo-ch/react-easy-crop#7]
open the demo page and change the aspect state using the react dev tools

the cropper should update its gutter according to the new aspect ratio, but it does not, the gutter does not change.

**Comment by ValentinH** [comment]
Hi! Thanks for creating the first (real) issue on this project! 🎉 

Indeed, changing the aspect at runtime is not supported at the moment. You can only set it during initialization. Do you have a use case where you need to set the aspect at runtime?

This isn't hard to implement, only to add a new switch case in the `componentDidMount()` to update the UI accordingly.

**Comment by mbretter** [comment]
Sure, I'm writing an uploader where the user can crop the image by choosing the aspect from a dropdown.

I like your package, because it is slim and easy to use, does exactly what we need (besides the aspect issue).

cheers

**Comment by ValentinH** [comment]
OK it makes sense.

PR on its way 😉

**Comment by ValentinH** [comment]
Just a quick demo of what I'm going to merge in master: https://codesandbox.io/s/l5r270r19q 

On this demo, the slider changes the aspect. 🎉
