### ISSUE TITLE
save the images

### ISSUE THREAD

**Issue by charlesprolife** [ricardo-ch/react-easy-crop#70]
## Are you reporting a bug?

- Please create a CodeSandbox that demonstrates your issue. You can fork the [Basic example](https://codesandbox.io/s/q80jom5ql6).

- Provide the steps to reproduce the issue, e.g.:

  1.  Move the image
  2.  Resize the window

  **Observed behaviour:** The cropper is outside the image

  **Expected behaviour:** The cropper stays within the image

## Are you making a feature request?

- Please describe your use case from user journey point of view, e.g.:

  > In my application, when user use the cropper on mobile, I'd like her to be able to zoom without the slider.

- If you have ideas how to implement your new feature, please share!

- If you know any examples online that already implement such functionality, please share a link.

**Comment by ValentinH** [comment]
@charlesprolife please provide a description.the template is here to inspire you, not to replace your description.
