### ISSUE TITLE
Crop mask is too small for vertical images 

### ISSUE THREAD

**Issue by TrebuhD** [ricardo-ch/react-easy-crop#71]
If an image is very tall, it seems to want to fit the image inside the canvas by shrinking the crop mask. I would like the mask to remain bigger, and the image to be outside the canvas viewport until the user zooms out. Is that possible?

I'm using `restrictPosition={false}` and `minZoom={0.9}`.

Here's how it looks when the image is loaded: 

![image](https://user-images.githubusercontent.com/7022085/67390482-055a8600-f59d-11e9-94f2-a2bce0c8d266.png)

and after zooming in: 

![image](https://user-images.githubusercontent.com/7022085/67390507-11dede80-f59d-11e9-80a7-e0e5ac53c4d6.png)

**Comment by ValentinH** [comment]
Hi, indeed you have a good point. I've just tried with a very tall image and the crop area is really really small.

I'm not sure how to address this though. Maybe we could define a minimum crop area size that would automatically set the zoom to match this area. 

Any other suggestion?

**Comment by TrebuhD** [comment]
That indeed sounds like a solution. Alternatively, the crop area size could also be defined as a fraction of the canvas size. That is, setting `cropMaskSize={0.9}` would make it occupy 90% of the canvas (if aspect ratios match).

Though for my use case, even a boolean prop like `maximizeCropMask` that would make it match the x/y size of the canvas would do.

**Comment by ValentinH** [comment]
I like the boolean approach. I'm still not sure on the naming though. It could be like a `mode` that would default to today's behavior (fitting the image to the canvas). Other value would be your request: fitting the crop area to the canvas.

Would you like to work on a pull request for this?

**Comment by kpheasey** [comment]
@TrebuhD I got around this using the `cropSize`, it sets the size of the crop-mask.  Here's a quick copy/paste sample, sorry for the noise, but the basic idea is there.  

```
...
const cropContainer = useRef();
const cropSize = ({ aspect }) => {
  if (!cropContainer.current) return undefined;

  return aspect === aspectLandscape ? ({
    width: cropContainer.current.clientWidth,
    height: cropContainer.current.clientWidth / aspectLandscape,
  }) : ({
    width: cropContainer.current.clientHeight * aspectPortrait,
    height: cropContainer.current.clientHeight,
  })
};

return (
  <Cropper
    key={values.gallery_crop.aspect}
    image={file.url}
    crop={{ x: values.gallery_crop.x, y: values.gallery_crop.y }}
    zoom={values.gallery_crop.zoom}
    cropSize={cropSize(values.gallery_crop)}
    onCropChange={form.mutators.setCrop}
    onCropComplete={input.onChange}
    onZoomChange={form.mutators.setZoom}
    rotation={rotation}
    restrictPosition={false}
  />
)
```

**Comment by ValentinH** [comment]
@kpheasey thanks for sharing this! How do you set the initial zoom? Do you ensure that the image fits the container horizontally or vertically?

**Comment by kpheasey** [comment]
@ValentinH You can calculate the initial zoom if you know the source image aspect ratio and the target aspect ration:

The following is how we calculate the zoom and crop.  We use this to set a minimum zoom, ensuring users cannot zoom out to a point where the image is no longer covered by the cropping area.

```js
const aspectLandscape = 16 / 9;
const file = { width: 1080, height: 1920 };

const zoom = (aspectLandscape / (file.width / file.height));
const crop = file.width > file.height ? ({
  x: 0, 
  y: file.width / 2,
}) : ({
  x: file.height / 2,
  y: 0,
})
```

**Comment by TrebuhD** [comment]
I can confirm that setting the `cropSize` works. Thanks all!

**Comment by ValentinH** [comment]
@TrebuhD so is this enough for your needs?

**Comment by TrebuhD** [comment]
Sure, that works well for me. Should we close this ticket?

**Comment by ValentinH** [comment]
Yes let's close it for now. If there is no blocker, I rather not add too many options to the library.

Would you like to create a codesandbox to demo what you did so I can add it to the examples?
