### ISSUE TITLE
Your Code has BUG

### ISSUE THREAD

**Issue by artFollower** [ricardo-ch/react-easy-crop#72]
When I sent in a compressed image, the image didn't show，I checked your code and solved it as follows:
![image](https://user-images.githubusercontent.com/26338398/67651089-71acff00-f97a-11e9-8fcc-f315a3cf58bb.png)
![image](https://user-images.githubusercontent.com/26338398/67651102-7c679400-f97a-11e9-8898-0d1d279c978a.png)

**Comment by artFollower** [comment]
When I pass a very large image, the image is black

**Comment by artFollower** [comment]
When I pass a very large image, the image capture is black.

**Comment by ValentinH** [comment]
Hello, thanks for reporting. What do you call a compressed image?
Could you provide a codesandbox showing the issue please?
