### ISSUE TITLE
setting cropSize affects restoration from initialCroppedAreaPixels

### ISSUE THREAD

**Issue by matthandlersux** [ricardo-ch/react-easy-crop#73]
it appears that the calculations done to restore the cropper's inner state from a previously saved `Area` (passed in through `initialCroppedAreaPixels`) are affected by passing in a fixed `cropSize`. 

- [example](https://codesandbox.io/s/react-easy-crop-example-with-local-storage-sync-i3beq?fontsize=14&hidenavigation=1&theme=dark). note that this is a fork of the demo from the readme ["Example with crop saved/loaded to/from local storage"](https://codesandbox.io/s/pmj19vp2yx), with the addition of one extra prop 
  ```jsx
  cropSize={{ width: 400, height: 400 }}
  ```

- Provide the steps to reproduce the issue, e.g.:

  1. Move the image so that the crop box appears at the top left (`{x: 0, y: 0}`):
  ![Screen Shot 2019-11-23 at 1 03 02 PM](https://user-images.githubusercontent.com/72524/69483139-c0bb4800-0df1-11ea-9000-9d858576c9c2.png)

  2. Reload the page 
  ![Screen Shot 2019-11-23 at 1 03 16 PM](https://user-images.githubusercontent.com/72524/69483145-cc0e7380-0df1-11ea-8615-e4a9140d2bc0.png)

  **Observed behaviour:** The cropper is no longer located at `{x: 0, y: 0}`

  **Expected behaviour:** The cropper is still located at `{x: 0, y: 0}`

**Comment by ValentinH** [comment]
Thanks for the clear issue.

I think that adding support for the `cropSize` prop was the biggest mistake I made. Almost all issues are related to this.

I'm trying to see what the issue is.

**Comment by ValentinH** [comment]
@matthandlersux https://github.com/ricardo-ch/react-easy-crop/releases/tag/v1.16.2 should fix this. Could you please confirm? :)

**Comment by matthandlersux** [comment]
@ValentinH looks like that fixed it on my end. thanks for the fast turnaround!
