### ISSUE TITLE
Feature: custom cropShape prop

### ISSUE THREAD

**Issue by yongyi520** [ricardo-ch/react-easy-crop#78]
Can we have custom crop shape passed in through cropShape prop? 

- Potential idea for implementing it (to add extra option for cropShape prop, css class or styleObject) :
![Screen Shot 2019-12-05 at 10 40 09 PM](https://user-images.githubusercontent.com/10789851/70250270-3808b880-17b0-11ea-97b9-1f01855f4ea6.png)

- square has custom css called 'css-nikas5'
![Screen Shot 2019-12-05 at 10 19 43 PM](https://user-images.githubusercontent.com/10789851/70249304-c7ad6780-17ae-11ea-8c8d-bf796607b838.png)

- circle has custom css called 'css-5xmhn'
![Screen Shot 2019-12-05 at 10 20 20 PM](https://user-images.githubusercontent.com/10789851/70249283-c2501d00-17ae-11ea-804d-45837e1c3c9a.png)

- I have been using your library in my app for client. The client would like to have a heart shape crop. Thought it would be a nice feature to have if possible

**Comment by ValentinH** [comment]
Hey, yes why not! What kind of data would you pass though to draw a heart?

**Comment by RaedsLab** [comment]
> Hey, yes why not! What kind of data would you pass though to draw a heart?

How about an SVG path?

**Comment by ValentinH** [comment]
I think it's actually already possible to achieve what you want by using the `style` (cropAreaStyle)  or the `classes` (cropAreaClassName) props.

**Comment by yongyi520** [comment]
Hi @ValentinH 

I have tried to pass in classes prop but i don't see classNames showing up
<img width="546" alt="Screen Shot 2019-12-06 at 12 09 40 PM" src="https://user-images.githubusercontent.com/10789851/70297605-61adf800-1821-11ea-9293-b02bd1bf1509.png">

<img width="329" alt="Screen Shot 2019-12-06 at 12 11 17 PM" src="https://user-images.githubusercontent.com/10789851/70297648-87d39800-1821-11ea-9ca1-d1c503213069.png">

Am I doing something wrong?

**Comment by ValentinH** [comment]
Yes the prop should be `classes` and not `class`. Also please not that mediaClassName requires version 1.17.0 (it was called imageClassName before).

**Comment by yongyi520** [comment]
Thank you @ValentinH that did fix my prop bug!

I needed heart-shape css (https://www.hongkiat.com/blog/css-heart-shape/) and it seems like the heart shape extends outside of the square with pseudo elements and it did not look right

<img width="371" alt="Screen Shot 2019-12-06 at 1 37 50 PM" src="https://user-images.githubusercontent.com/10789851/70301682-a344a000-182d-11ea-87ff-48c5f6cbd807.png">

Is there a way to pass a child element or svg inside the cropShape div? That way the heart shape will be contained inside the cropped area. 

Sorry for extra ask

**Comment by ValentinH** [comment]
Could you please provide a codesandbox (from this template: https://codesandbox.io/s/react-easy-crop-v69ly910ql) that show what you've tried?

**Comment by yongyi520** [comment]
https://codesandbox.io/s/affectionate-banach-x2p7e. Somehow the circles were not aligned properly, but the psudo elements that extended outside of the square

wanted result:
heart shape inside of the square box

**Comment by ValentinH** [comment]
I'm sorry but I don't think this library should support this use case. I don't want to overload it with to many features.
