### ISSUE TITLE
Order of transformations for back-end service

### ISSUE THREAD

**Issue by raRaRa** [ricardo-ch/react-easy-crop#84]
Hi. I'm trying to replicate what `react-easy-crop` is doing with the image on my back-end service. I'm wondering in what order the transformations are made, e.g. do you adjust the aspect ratio first, then rotate and then finally crop? I managed to replicate the cropping & zoom fine, but the image always looks offset when I use rotation on my back-end service.

Thanks!

**Comment by ValentinH** [comment]
Hi,

You can have a look at the `cropImage.js` file in this codesandbox: https://codesandbox.io/s/q8q1mnr01w that does exactly what you want to do, but on the frontend.

**Comment by raRaRa** [comment]
Thanks @ValentinH - that helped!

Here's the code I ended up using for .NET Core `ImageSharp`

```
// Begin by fixing the orientation of the photo
image.Mutate(m => m.AutoOrient());

// Create a transformation that rotates the photo in the center by degrees
var affineBuilder = new AffineTransformBuilder();
affineBuilder.AppendRotationDegrees(cropRect.RotationDegrees, new Vector2(image.Width / 2, image.Height / 2));

// Next mutate the image by applying the rotation transformation and then crop.
image.Mutate(m => m
    .Transform(affineBuilder)
    .Crop(
        new Rectangle(
            Convert.ToInt32(cropRect.X),
            Convert.ToInt32(cropRect.Y),
            Convert.ToInt32(cropRect.Width),
            Convert.ToInt32(cropRect.Width)
        )
    )
);
```

Hope this helps anyone else in the future.

**Comment by ValentinH** [comment]
You're welcome, thanks for sharing! 👏
