### ISSUE TITLE
How to disable mouse wheel ?

### ISSUE THREAD

**Issue by chitayezaw11** [ricardo-ch/react-easy-crop#86]
I want to remove mouse wheel scrolling for zooming. I just need drag up and down. When I remove zoom, it doesn't zoom but image is moving around outside div. The best way for my need is to remove mouse wheel event.

**Comment by ValentinH** [comment]
Thanks for this issue. I'll try to look into it ASAP.

**Comment by ValentinH** [comment]
Well caught, I fixed it and released it with 1.17.1 :)
