### ISSUE TITLE
Saving cropped image

### ISSUE THREAD

**Issue by matveychuk** [ricardo-ch/react-easy-crop#9]
Can you tell me how I can save cropped image as blob to upload it to AWS-3 later?

**Comment by ValentinH** [comment]
This example shows how to get the Blob (or base 64) of the cropped image: https://codesandbox.io/s/q8q1mnr01w

Check the `getCroppedImg()` function 🙂.

**Comment by matveychuk** [comment]
@ValentinH thanks a lot for prompt reply! will check it)

**Comment by matveychuk** [comment]
Yes, thank you!

ср, 1 авг. 2018 г. в 22:25, Valentin Hervieu <notifications@github.com>:

**Comment by miltonbo** [comment]
I'd suggest adding the `cropImage.js` file to the lib.

**Comment by ValentinH** [comment]
I'm often hesitating to do so indeed. Originally, I didn't want to include it because it's a quite complex logic that I'm not willing to maintain. However, I get a lot of issues about it and I still provide support. So the result is the same anyway 😆

**Comment by miltonbo** [comment]
Right, either way you are supporting it.
