### ISSUE TITLE
v2 should re-export types from ./types?

### ISSUE THREAD

**Issue by hlian** [ricardo-ch/react-easy-crop#90]
Hi! Big fan on the library. On v2, it's difficult to write down the types for the callbacks because these types

```typescript
import { Area, MediaSize, Point, Size } from './types';
```

aren't re-exported from `index.d.ts`. Let me know if I'm doing something dumb!

**Comment by ValentinH** [comment]
Hi thanks for the kind words. They are actually exported in types.d.ts so you can do 'import { Area } from 'react-easy-crop/types'`.

If you think this is weird, I might consider exporting them in the index as well :)

**Comment by hlian** [comment]
oh gotcha! thank you

**Comment by ValentinH** [comment]
Do you think this should be documented in the Readme?

**Comment by hlian** [comment]
perhaps? wouldn't hurt!
