### ISSUE TITLE
Example for cropping video

### ISSUE THREAD

**Issue by Sensiblemnd** [ricardo-ch/react-easy-crop#92]
Need examples on cropping video

**Comment by ValentinH** [comment]
I've just added one to the readme: https://codesandbox.io/s/react-easy-crop-for-videos-lfhme

**Comment by formalinfigs** [comment]
> I've just added one to the readme: https://codesandbox.io/s/react-easy-crop-for-videos-lfhme

This example does not work for me, I see a blank screen
![image](https://user-images.githubusercontent.com/31365113/75017764-cb43b700-549e-11ea-8ddf-79998601d15f.png)

**Comment by ValentinH** [comment]
Hi, this is weird: I just tried it and it works fine for me (Chrome and Brave). What browser are you using?

**Comment by formalinfigs** [comment]
@ValentinH Hi :)
![image](https://user-images.githubusercontent.com/31365113/75025407-31830680-54ac-11ea-9daa-5523defe9877.png)

**Comment by ValentinH** [comment]
Did you try in "Private" mode? Or with another browser?

**Comment by formalinfigs** [comment]
I think it's my problem connected with extensions. Thanks :)

**Comment by Sensiblemnd** [comment]
I also got a blank screen. 

Problem is with the example video. 
Video link is HTTP instead of HTTPS

**Comment by ValentinH** [comment]
Yes you are right. It's done :)

**Comment by n-zamani** [comment]
How to get the cropped video to upload? the example with canvas returns a png file.
