### ISSUE TITLE
Get ref to the image element

### ISSUE THREAD

**Issue by Michal-Sh** [ricardo-ch/react-easy-crop#96]
Hi,
First of all, thanks for your package its really comfortable.
I would like to have an ability to get a ref for the image element (maybe to add a prop `imageRef` or something similar)
Is it possible?

**Comment by ValentinH** [comment]
Thanks for the kind words!

Giving you access to the image ref is quite tricky because there is already one that is used internally. I need to think about it.

Just to understand, what use case are you trying to cover?

**Comment by Michal-Sh** [comment]
Thanks for the quick response, 👍 
Actually, meanwhile I got along with that.

**Comment by ValentinH** [comment]
So can we close this?

**Comment by Michal-Sh** [comment]
Sure

**Comment by blyszcz** [comment]
I wanted to crop the image on client-side with this code:
```
/**
 * @param {HTMLImageElement} image - Image File Object
 * @param {Object} crop - crop Object
 * @param {String} fileName - Name of the returned file in Promise
 */
function getCroppedImg(image, crop, fileName) {
  const canvas = document.createElement('canvas');
  const scaleX = image.naturalWidth / image.width;
  const scaleY = image.naturalHeight / image.height;
  canvas.width = crop.width;
  canvas.height = crop.height;
  const ctx = canvas.getContext('2d');
 
  ctx.drawImage(
    image,
    crop.x * scaleX,
    crop.y * scaleY,
    crop.width * scaleX,
    crop.height * scaleY,
    0,
    0,
    crop.width,
    crop.height,
  );
 
  // As Base64 string
  // const base64Image = canvas.toDataURL('image/jpeg');
 
  // As a blob
  return new Promise((resolve, reject) => {
    canvas.toBlob(blob => {
      blob.name = fileName;
      resolve(blob);
    }, 'image/jpeg', 1);
  });
}
```

And I do need a reference to an image, @ValentinH do you plan to add this feature?

**Comment by ValentinH** [comment]
You should find what you need in the Codesandbox examples 😉

**Comment by OmarOmeiri** [comment]
> Thanks for the kind words!
> 
> Giving you access to the image ref is quite tricky because there is already one that is used internally. I need to think about it.
> 
> Just to understand, what use case are you trying to cover?

Hey Valentin, I have a use case for this.
 I'd like to calculate the image size before the user accepts the image crop. Thus I need access to the container and Image `DOMRect` this way I can calculate how much of the image is going to be thrown out. I there any way of doing this easily? Thanks!

**Comment by OmarOmeiri** [comment]
> > Thanks for the kind words!
> > Giving you access to the image ref is quite tricky because there is already one that is used internally. I need to think about it.
> > Just to understand, what use case are you trying to cover?
> 
> Hey Valentin, I have a use case for this.
> I'd like to calculate the image size before the user accepts the image crop. Thus I need access to the container and Image `DOMRect` this way I can calculate how much of the image is going to be thrown out. I there any way of doing this easily? Thanks!

I solved it by adding a `ref` to a parent div and doing the following:

```
  useEffect(() => {
      if (imgSize && containerRef.current) {
        const size = predictImgSize(imgSize, imgQuality, 0.3);
        const grid = containerRef.current.querySelector('.reactEasyCrop_CropAreaGrid');
        const img = containerRef.current.querySelector('.reactEasyCrop_Image');
        if (grid && img) {
          const gridRect = grid.getBoundingClientRect();
          const imgRect = img.getBoundingClientRect();
          const gridArea = gridRect.height * gridRect.width;
          const imgArea = imgRect.height * imgRect.width;
          const imgAreaRelative = Math.min((gridArea / imgArea), 1);
          setImgPredictSize(`${(imgAreaRelative * size).toFixed(1)} MB`);
        }
      }
  }, [imgSize, imgQuality, zoom, aspectRatio]);
```

But I cringe everytime i have to do `document.querySelector` or `document.getElement...` in React. So it would be nice to have access to these `refs`.

Thanks

**Comment by ValentinH** [comment]
I just remembered about the `onMediaLoaded` option , did you try it? It passes the image sizes (including the natural size). If you also need the grid size, we could add it to this function parameters.

**Comment by OmarOmeiri** [comment]
> I just remembered about the `onMediaLoaded` option , did you try it? It passes the image sizes (including the natural size). If you also need the grid size, we could add it to this function parameters.

Yes, but for my use case I need the area every time the user changes the zoom or the aspect ratio. So `onMediaLoaded` would not cut it. But thanks for the time to respond and the willingness to help! Very rare traits found with package owners/collaborators. Congratulations for the awesome package.

**Comment by ValentinH** [comment]
Ok then I think we could add a custom prop for getting the image/video ref. I guess we could just accept an `imageRef` props and set it in [this line](https://github.com/ricardo-ch/react-easy-crop/blob/main/src/index.tsx#L519) if it is defined.

Would you like to make a PR for this?

**Comment by OmarOmeiri** [comment]
> Ok then I think we could add a custom prop for getting the image/video ref. I guess we could just accept an `imageRef` props and set it in [this line](https://github.com/ricardo-ch/react-easy-crop/blob/main/src/index.tsx#L519) if it is defined.
> 
> Would you like to make a PR for this?

I'll check it out!

**Comment by AbeCole** [comment]
Hi I'm interested in something similar for the 'Video' element. Specifically it's to control the playback of the video.

I was thinking simply pass the videoRef in our call to `this.props.onMediaLoaded` on line 191 might work? i.e. `this.props.onMediaLoaded(this.mediaSize, this.videoRef)` or possibly to accommodate both Image/Video `this.props.onMediaLoaded(this.mediaSize, this.imageRef || this.videoRef)`

Have just given this a test on a [fork](https://github.com/AbeCole/react-easy-crop) and it works for my purpose, but maybe there is a better way?

**Comment by ValentinH** [comment]
This is also a possible approach but I guess to easiest and also the more flexible for users would be to accept both an `imageRef` and a `videoRef` that we attach the corresponding ref to.
