### ISSUE TITLE
Prevent zoom by scroll

### ISSUE THREAD

**Issue by Michal-Sh** [ricardo-ch/react-easy-crop#99]
Hi,
I would like to prevent changing the zoom by scrolling because in my case it's disturbing the page scrolling.
Does there is support for such an option or do you any idea for me to implement it?
Thanks
BTW, I really like this package 😍 .

**Comment by ValentinH** [comment]
Hello,

You can completely disable the zoom logic by not setting the `onZoom` callback.
However, it will also disable the zoom on mobile (using gestures).

If you want, you could do a PR to add an new "prop" to disable the zoom with scroll :)

**Comment by Michal-Sh** [comment]
Thanks a lot! it's a really easy solution for now.
If so, do you want me to do that PR?

**Comment by ValentinH** [comment]
If you really need it, yes you can do it. 🎉 

Otherwise, we can wait for someone to need it to avoid adding extra logic.

**Comment by Michal-Sh** [comment]
Alright, for the current case the above solution is enough for me.
Thanks again for the great support!

**Comment by Michal-Sh** [comment]
Hi, 
In a second thought - I actually need it, 
Could you reopen it?

**Comment by ValentinH** [comment]
Sure.
What API would you suggest for this option?

**Comment by Michal-Sh** [comment]
As you said before:
>If you want, you could do a PR to add an new "prop" to disable the zoom with scroll :)

Adding a new 'prop' for that will be perfect for me.

**Comment by ValentinH** [comment]
Alternatives I have in mind:
- `disableZoomOnScroll`
- `mobileZoomOnly`
- `zoomWithScroll` (true by default)

Any other ideas?

**Comment by Michal-Sh** [comment]
Perfect! I most like the last one.
Can I do that?

**Comment by ValentinH** [comment]
Sure, PR are welcome! :)
